### ISSUE TITLE
Change Password of User

### ISSUE THREAD

**Issue by KeKl** [themotleyfool/Klondike#101]
Hi,

where do I change the password for created users?

Regards,
Kevin

**Comment by chriseldredge** [comment]
Klondike does not manage passwords but does manage Api Keys. You can view and change them by accessing the web admin in a browser and navigating to Admin.

**Comment by pdfforge** [comment]
Maybe it is a question of a common understanding, but when clicking on the "Sign In", the user is asked for username and password. I assume that this has a good reason, despite the fact that there are no passwords. Probably that's where the question from KeKl comes from (and I have the same).

What is the user supposed to enter in that login screen? Or would we need to configure an authentication method to be able to login there?
