### ISSUE TITLE
If I use the settings from the readme the server wont start

### ISSUE THREAD

**Issue by hvanbakel** [themotleyfool/Klondike#105]
The link in the readme points to:
https://github.com/themotleyfool/Klondike/blob/master/src/Klondike.WebHost/Settings.config

however if you paste those appsettings into release 1.6.2, you will get an error that no owin:AppStartup is defined. 

I had to add this:
```Xml
    <add key="owin:AppStartup" value="NuGet.Lucene.Web.SignalRStartup" />
```

**Comment by chriseldredge** [comment]
The README documents the latest beta version (2.0) and will not work correctly when trying to follow along using 1.6.2.

**Comment by hvanbakel** [comment]
I see, but wouldn't it be better to have the settings documented on the
readme at least have a version if you have 2.
