### ISSUE TITLE
Restricting read-access (Windows Authentication, IIS)

### ISSUE THREAD

**Issue by dee-see** [themotleyfool/Klondike#110]
I have to restrict read access to our packages very much like #66.

I am doing it like this:

    <system.web>
    ...
        <authorization>
            <allow roles="active directory role" />
            <deny users="*" />
        </authorization>
    </system.web>

With this configuration, the call to `/api/session` fails with a 401 Unauthorized (I get a login box, my credentials don't work), yet the response body contains my credentials anyway.

    {
      "username": ...,
      "key": ...,
      "roles": [
        "PackageManager",
        "AccountAdministrator"
      ]
    }

Now if I click on the "Sign In" link at the top my username appears and everything seems fine. I can browse to the Admin page and see the Synchronize Packages and Rebuild Index buttons, but when I click them the login box reappears and my credentials are always refused. I get this issue with and without `roleMappings`. It's the `<deny users="*" />` configuration that makes this behaviour appear, without it everything works fine.

I am using build 119 but I have the same issue when using the Klondike-Release branch's binaries.

**Comment by chriseldredge** [comment]
Have you tried disabling Anonymous Authentication in IIS instead of changing system.web/authorization?

You may also get different results using the newer system.webServer/security config section.

**Comment by dee-see** [comment]
Disabling Anonymous Authentication does not help. I need the `<deny users="*" />` anyway with my `<allow>` because I want to restrict access to a specific role.

Moving my authorization rules to the `system.webServer/security` section does not change the behaviour.

**Comment by chriseldredge** [comment]
What version of Klondike are you using?

**Comment by dee-see** [comment]
Build 119 but I have the same issue when using the Klondike-Release branch's binaries.

**Comment by chriseldredge** [comment]
Upon investigation it turns out that Api Key authentication was replacing instead of augmenting role grants. As a result, role based security stops working when disabling Anonymous Authentication and sending a valid `X-NuGet-ApiKey` header.

**Comment by chriseldredge** [comment]
Build 124 should have a fix for this issue.

https://ci.appveyor.com/project/chriseldredge/klondike/build/124/artifacts

**Comment by dee-see** [comment]
Great, thank you very much!
