### ISSUE TITLE
Add possibiliy update paket within klondike

### ISSUE THREAD

**Issue by BADF00D** [themotleyfool/Klondike#116]
I recently wanted to upgrade a package to a newer version on nuget.org. Unfortunately the package manager within Visual Studio did not display this package, when using klondike as source server. So I visit the package page on klondike but can't find an option to upgrade the mirrored package.

The only possibility I found was using the API page by using the "Download package" command and specify the new version. This is a possible way, but I think there should be a more obvious way.

What do you think?

**Comment by chriseldredge** [comment]
Please see my comment on a related issue: https://github.com/themotleyfool/Klondike/issues/109#issuecomment-135883363

I agree it would be nice if Klondike could offer the union of all local packages and packages in a remote mirror, but the feasibility of implementing such a design comes to question.

**Comment by chriseldredge** [comment]
Also please note you will get better results on the Visual Studio NuGet Package Manager Console using the Update-Package cmdlet.  Using tab completion in the `-Version` value should offer version in the remote that have not yet been mirrored.
