### ISSUE TITLE
Username with special characters have encoding errors

### ISSUE THREAD

**Issue by pdfforge** [themotleyfool/Klondike#117]
When creating a user with a special character (i.e. German umlauts), these characters are not encoded properly somewhere on the way, I have not fully tracked this down though.

When creating a user "Jöhn", it is displayed as "JÃ¶hn", which basically is UTF-8 display as Windows-1252. It could be that this can be fixed by forcing the webpage codepage to UTF-8.

**Comment by chriseldredge** [comment]
Looks like the encoding is bad going in or during serialization coming out.

```
curl -i http://localhost:4201/api/users
HTTP/1.1 200 OK
Content-Length: 277
Server: Nowin
Date: Sat, 07 Nov 2015 16:37:01 GMT
Content-Type: application/json; charset=utf-8

[
  {
    "username": "JÃ¶hn",
    "key": "fccc9cd3-a38a-441a-932b-a88961cba5a8",
    "roles": []
  }
]
```

**Comment by chriseldredge** [comment]
User name is bound to URL path as in `PUT /api/users/J%C3%B6hn`. When decoded, that's `PUT /api/users/JÃ¶hn`.

I guess I'll go read the spec about character encoding URI paths.

**Comment by chriseldredge** [comment]
The problem seems to be on retrieval. Adding a user at `/api/users/J%C3%B6hn` stores the string as UTF-8, but the browser seems to use the incorrect character encoding when deserializing JSON from `/api/users`.

**Comment by chriseldredge** [comment]
Are you running Klondike on Mono? I can only reproduce this problem on OS X / Mono. Windows builds seem to work correctly.

**Comment by pdfforge** [comment]
thank you for looking into this!

We are running Klondike in standalone mode on Windows 7. As the browser might be involved there: I tested it with recent versions of Firefox and Chrome.

**Comment by chriseldredge** [comment]
Confirmed this problem affects self-hosted Klondike but not IIS web-hosted. It also doesn't appear to affect NuGet.Lucene.Web.OwinHost.Sample which leads me to think upgrading some packages may resolve the issue for Klondike.

**Comment by chriseldredge** [comment]
Upgraded and added some self-host dependencies in 9ea8a7885a3b7fa19ee9deabb86c4049f825c1be and verified this fixes the problem.

**Comment by pdfforge** [comment]
Thank you for looking into this so quickly :)

I have updated our build and it works perfectly now. Once again: Thank you very much!

PS: In case you are having a list of Klondike users: PDFCreator (http://www.pdfforge.org/pdfcreator) will move to Klondike very soon, it is in pre-production right now
