### ISSUE TITLE
Load balancing recommendations

### ISSUE THREAD

**Issue by pvandervelde** [themotleyfool/Klondike#118]
As mentioned in #85 Klondike isn't designed to be run in a clustered configuration, however #88 indicates that it is possible to run multiple instances of Klondike pointing at the same packages folder (but maybe not the same symbol folder / location?). So if I would want to run Klondike in a redundant setup what would be the most sensible setup.

The only options that I can think of is using a master - slave approach like in #88, i.e. the master is the only one that is allowed to do writes while the slaves are will only do reads. This will provide read load balancing while still maintaining data store consistency. If the master experiences a failure the write capability would disappear (and potentially the data store could be damaged?). In this case it could potentially be possible to turn one of the slaves into a master by allowing it to write to the data store (but that might create issues with the meta data?).

Are there any other recommended approaches that we as users can apply with the current state of Klondike?

And a semi-related question: what parts of the Klondike design are not designed for clustering. Is it only the symbol server side (as far as I'm aware the symstore tool isn't able to handle simultaneous transactions) or are there other bits that are not able to handle multiple simultaneous writes?

**Comment by chriseldredge** [comment]
Using a CIFS share to hold packages and symbols should allow multiple instances of Klondike to server a consistent view of packages and symbols, provided that Klondike's filesystem watcher is enabled to automatically index packages as they are added to the share.

I haven't tested this configuration but am not aware of any reason this would not work both for packages and symbols.

Each instance of Klondike should have its own Lucene directory to hold package metadata, and this is kept in sync using the file system watcher.

The primary storage that will not work correctly in a cluster is the Lucene index that stores api keys and permissions.

This, of course, makes the CIFS share a single point of failure. This could be mitigated by hosting the share on a high-availability NAS or similar appliance.

To build first-class support for clustering and high availability into Klondike, one approach I would explore would be using ZooKeeper for leader election, then have followers forward writes to the current leader. This would also require a replication api that would allow followers to receive, or even participate in transactions.

While that sounds like a fun project, I have no time whatsoever to start on such an initiative.

**Comment by pvandervelde** [comment]
That sounds like a good approach. Is the symbol store able to handle writes from multiple locations? And what about the Lucene user data (like API keys etc.) can those be shared?

When I have some time I will experiment with the suggested set up and see what happens when I hammer it. I will report back if I find anything unusual so that we have a record of what works and what doesn't for those of us (like me) who want to use Klondike outside of the design boundaries :)

**Comment by chriseldredge** [comment]
I think there are one or two shared files that get updated when pushing symbol packages so that would probably trigger failures if you are trying to publish lots of symbol packages concurrently. This may already be the case with a single instance of Klondike.

The API keys are not easy to share/replicate at this time. I don't have a good suggestion for how to keep them in sync, other than devising a manual process.
