### ISSUE TITLE
Big packages cannot be uploaded in SelfHosting mode

### ISSUE THREAD

**Issue by Stift** [themotleyfool/Klondike#121]
I just played a little bit around with the latest beta and found that when I wanted to upload a FAKE package which is 12MB large the push times out. In the Packages\.tmp folder is for each try a file of around 6.3MB created, but the upload fails. When I host the latest beta in IIS upload works fine. I assume there is a request size limit.

**Comment by chriseldredge** [comment]
Request times out after 7 minutes in a test and hangs after transferring 13041508 bytes.

**Comment by chriseldredge** [comment]
Bug seems to only be triggered when using Nowin.

`Klondike.SelfHost.exe --serverFactory=Microsoft.Owin.Host.HttpListener` accepts large packages without problems.

**Comment by chriseldredge** [comment]
Fixed in commit da10b2a74e6958dd7ae0b0cd0607deeeca735ac0 and [build 141](https://ci.appveyor.com/project/chriseldredge/klondike/build/141/artifacts).
