### ISSUE TITLE
Only allow specific request to search for packages [Feature Request]

### ISSUE THREAD

**Issue by Stift** [themotleyfool/Klondike#122]
On the front page it is claimed "storing your private packages privately". This is only true, when I host Klondike in some closed environment.
Generally all packages are open for everyone who requests the api. We should be able to create api keys for searching and downloading as well. These api keys should follow its own semantic and not allow pushes and only exist for developers who download a package. With this feature a Klondike server could really serve as private feed.

**Comment by chriseldredge** [comment]
Perhaps the language is ambiguous, but it is meant to communicate that Klondike, when deployed on a private network, can host an organization's private packages privately.

If you want software that allows multiple users to have separate permissions to view their own package feeds in a single instance of Klondike, it does not do that.

**Comment by Stift** [comment]
This was not exactly what I meant. It was more like that you are able to protect the feed against unauthorized access. It was more in a way to not only use the api key for uploading also for searching/downloading packages. 
Maybe this could be a new role, e.g. 'PackageConsumer'.
