### ISSUE TITLE
Allow Search parameter NormalizedVersion

### ISSUE THREAD

**Issue by pdfforge** [themotleyfool/Klondike#124]
When using Paket (https://github.com/fsprojects/Paket) to resolve our dependencies, I get this HTTP command:

     GET /api/odata/Packages?$filter=(Id%20eq%20'pdfcmon')%20and%20(NormalizedVersion%20eq%20'0.8.4')

Klondike does not understand the parameter NormalizedVersion though. The basic problem ist that we have a dependency that is required with version 0.8.4.0, Paket queries with the normalized version 0.8.4 and this can't be resolved.

Would it be possible to add the search for NormalizedVersion?

**Comment by chriseldredge** [comment]
Yes, it's certainly possible. Is there any documentation that explains the difference between `Version` and `NormalizedVersion`, and rules for determining equality?

**Comment by pdfforge** [comment]
I could not really find documentation on it and digging through the NuGet Source does not clarify too much. From what I understood, trailing zeros are cropped, so 1.2.0.0 would be equal to 1.2 and 1.2.3.0 would equal 1.2.3.

**Comment by chriseldredge** [comment]
Added in d92c239703769b44be65c00fbc30a162c1d1b814 and [build 141](https://ci.appveyor.com/project/chriseldredge/klondike/build/141/artifacts).
