### ISSUE TITLE
Multiple Feeds?

### ISSUE THREAD

**Issue by bobready** [themotleyfool/Klondike#125]
NuGet.Lucene was only able to host a single NuGet feed last we looked at it. Can Klondike host multiple feeds with different permissions for each?

Thanks!

**Comment by chriseldredge** [comment]
Nope. The best alternative option would be to deploy multiple instances of Klondike.

**Comment by tinuroth** [comment]
Any news on that topic? Multiple feeds would be a nice enhancement!
