### ISSUE TITLE
Slow download rates with SelfHost

### ISSUE THREAD

**Issue by danm-de** [themotleyfool/Klondike#126]
Hi,

we use Klondike started as Selfhost (Microsoft.Owin.Host.HttpListener). Unfortunately the (package) download rates are very slow (about 230 kbps).

Do you have any ideas how we can speed up the downloads? Searching / Indexing is pretty fast.
Any hints where I can start debugging?

Greetings,
Daniel

**Comment by chriseldredge** [comment]
I'm not aware of such an issue. You could try swapping out the Nowin server factory to see if that helps.

See the `serverFactory` option in the self-host readme:
https://github.com/themotleyfool/Klondike/blob/master/src/Klondike.SelfHost/README.md

**Comment by danm-de** [comment]
I've updated to the newest Klondike version today (current master), replaced my customized web.config with the default one, started the self-host executable as "domain user" instead of "LocalSystem" (Windows service) and the problem seems solved. \o/

Thanks!

Daniel
