### ISSUE TITLE
NuGet update -Safe or isMaxInclusive=false not working right?

### ISSUE THREAD

**Issue by Framnk** [themotleyfool/Klondike#127]
It seems that trying to constrain package updates using nuget update -Safe or FindPackage API with isMaxInclusive=false is not working correctly.

For instance if I search for a package with [1.0,1.1) it will still match on version 1.1 although it was not inclusive in the range.

**Comment by chriseldredge** [comment]
Which version of Klondike are you using?

**Comment by Framnk** [comment]
I am using 1.6.2

**Comment by chriseldredge** [comment]
Please try the recently released version 2.0 (https://github.com/themotleyfool/Klondike/releases/tag/v2.0.0).
