### ISSUE TITLE
Nuget package automapper 4.1.1 cause error

### ISSUE THREAD

**Issue by dguder** [themotleyfool/Klondike#131]
I can't use Klondike as a proxy to download and install [AutoMapper](https://github.com/AutoMapper/AutoMapper) [4.1.1](https://www.nuget.org/packages/AutoMapper/4.1.1), but AutoMapper 4.0.4 is working. In addition the fallback to another nuget source is not working.

Win7 64, .Net 4.5.2, Klondike 2.0 (either release or source), VS2013

Repro nuget.exe (version 3.3.0.212)

    X:\Klondike-test>nuget.exe install automapper
    Feeds used:
      http://localhost:8080/api/odata
    An error occurred while retrieving package metadata for 'automapper' from source 'http://localhost:8080/api/odata'.

Repro VS2013 Package Manager Console

    Package Manager Console Host Version 2.8.60723.765
    PM> Install-Package automapper
    Install-Package : Unable to find package 'automapper'.
    At line:1 char:1
    + Install-Package automapper
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
        + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
     
The only log entry for this in Klondike is following:
`2015-12-17 09:13:21,387 [130] INFO  NuGet.Lucene.Web.Models.MirroringPackageRepository - Found package automapper at https://www.nuget.org/api/v2/`

I looked at Klonike and Nuget.Lucene sources, but i could not find the code location where I can dig deeper.

**Comment by dguder** [comment]
I think it has something to do with Nuget.Core. When I use nuget.exe verison 3.3.0 then I can install Automapper 4.1.1 into a plain folder. But when I use nuget.exe 2.8.6 then I get following error:

    U:\Development\klondike-test>nuget2.exe install Automapper
    Attempting to resolve dependency 'Microsoft.Bcl (= 1.1.10)'.
    Attempting to resolve dependency 'Microsoft.Bcl.Build (= 1.0.14)'.
    Attempting to resolve dependency 'Microsoft.CSharp (= 4.0.0)'.
    The 'Microsoft.CSharp 4.0.0' package requires NuGet client version '3.0' or above, but the current NuGet version is '2.8.60717.93'.

So maybe [Nuget.Lucene](/themotleyfool/NuGet.Lucene) should handle this.

**Comment by chriseldredge** [comment]
This does appear to be a problem in the client. Latest client works correctly for me.

**Comment by dguder** [comment]
Just want to drop a note that with Klondike 2.1.1. and nuget package manager for VS 2013 version 2.12.0.812 the issue is gone. Thanks so far.
