### ISSUE TITLE
FireFox 43 cannot display Klondike

### ISSUE THREAD

**Issue by Stift** [themotleyfool/Klondike#132]
With FF43 there is a problem, that zou don't see anything. When I switch to the console I see an error saying: "None of the "sha512" hashes in the "integrity"-attribute is equal to the content of the subressource"

It seems like the hashes of the klondike...js files have not been recalculated after an update

**Comment by Stift** [comment]
When I change manually the hashes everything is working fine. I think in the build process the hashes should be adopted:

css Link
```
<link rel="stylesheet" href="assets/klondike-7f67066bb4903e9cc48ceb10752e1a11.css" integrity="sha256-M27tpUyndYa9GwHzg65I2hVkM/efNfOTURc0syVshLA= sha512-HsL38b87//BZb2A0Gl0MGX3b33mgIJAboQ0WvJih1+UKgUPjKJsg1LyGTDGHmAGU59ldX5MxPyxhv58J/2LkJQ==" >
````
js script include
```
<script src="assets/klondike-582cb400e65a3230b9c29cc41e8f27b5.js" integrity="sha256-RXqyNDpLfsd95Khwc7sh9GbIVfe4BhJNZ7q0HbZOMsE= sha512-ELwO8XRctZH0bIywmApYnUH8xT7nyFqv0wuRoasz9U+k8U9y3zo6r2yGu8lKKfb2ygD1jng8oBiPHfeif+99PQ==" ></script>
```

**Comment by Stift** [comment]
I think the same issue is described here: #128

**Comment by chriseldredge** [comment]
Just tried on Firefox 46 and could not reproduce. If you continue to have problems, feel free to reopen.

**Comment by Stift** [comment]
I just tried to build the current version, and the hashes generated seems to be correct, but in the repo Klondike-Release are these wrong and it seems like only for SHA512 hashes are wrong there.

**Comment by chriseldredge** [comment]
Ah, I figured out the git client on Windows is probably converting line endings on the javascript and css files to CRLF, which would invalidate the SHA hashes. I've added a `.gitattributes` to the Klondike-Release repo which should hopefully resolve this problem.
