### ISSUE TITLE
How to run SelfHost non-interactive?

### ISSUE THREAD

**Issue by eeevans** [themotleyfool/Klondike#133]
I installed it on a server without IIS and want to run Klondike self-hosted but want to logout.  I have put it in the Run key so that it will load on startup but I'd like to be able to control it without rebooting the server.  If I launch it now and log out, it stops running.

Thanks

**Comment by pdfforge** [comment]
Hi,

even though I usually hate RTFM posts, there is a quite good explanation in the self-host readme:
https://github.com/themotleyfool/Klondike/blob/master/src/Klondike.SelfHost/README.md

The most im portant part is to create a service (with sc.exe) that you can control and run without having a user logged in and of course you can also stop or restart this custom service any time.

Philip

**Comment by eeevans** [comment]
Hi Philip,
I usually hate being given RTFM answers second only to needing to be given RTFM answers.  You are quite right that the explanation in the README is quite good.  I swear I read it twice and missed that part.  Thank you most kindly for the RTFM post, and I apologize for wasting your time.

**Comment by pdfforge** [comment]
no need to apologize at all :)
