### ISSUE TITLE
When is a package considered mirrored?

### ISSUE THREAD

**Issue by pvandervelde** [themotleyfool/Klondike#134]
How does Klondike determine if a package is mirrored or local? In our instance Klondike has decided that we have only 8 mirrored packages, however a large number of the packages that Klondike considers local have been mirrored from nuget.org.

Listing all packages gets us:
![image](https://cloud.githubusercontent.com/assets/96201/12969276/1bc30aa8-d0e3-11e5-89f9-ec08d5d6928b.png)

Listing all mirrored packages gets us:
![image](https://cloud.githubusercontent.com/assets/96201/12969281/32b587ea-d0e3-11e5-802e-4f5b35b6eb59.png)

And listing all local packages gets us:
![image](https://cloud.githubusercontent.com/assets/96201/12969286/443fe8e8-d0e3-11e5-9276-d309e8f7b77a.png)

Searching for all packages authored by us gets us:
![image](https://cloud.githubusercontent.com/assets/96201/12969303/7b47115e-d0e3-11e5-96f4-25b6f2b1ece0.png)

Which seems far more reasonable. From that count there are nearly 500 packages that Klondike considers `local` that probably are mirrored from nuget.org. Is there a setting we can change that makes this work?

**Comment by ryager** [comment]
I agree with pvandervelde. It would be nice if we could clearly see which packages are truly only local to our server (maintained by us).

**Comment by Stift** [comment]
I experienced once, that this might happen, when you rebuild your index. Then klondike seems to read only the directory and forgot what is in the index.

**Comment by pvandervelde** [comment]
@Stift Ooooohhh that makes sense. We've had to rebuild the index.

**Comment by Stift** [comment]
I planned for myself to take a look into that issue. It's an odd thing.

**Comment by Stift** [comment]
BTW: Why did you need to rebuild the index?

**Comment by pvandervelde** [comment]
We had some packages that had to be deleted. I seem to recall that package deletions require index rebuilding.

**Comment by Stift** [comment]
Yeah I had similar issues in the past and deleting packages or marking them as deprecated would be a nice feature

**Comment by Stift** [comment]
A small workaround that I did at this time was, to delete every mirrored package from the folder, reindexing and let the client redownload the mirrored ones. Not a nice soution, but it worked at least

**Comment by pvandervelde** [comment]
Yeah fair enough. I will try that

**Comment by chriseldredge** [comment]
This is a bug that I've tried to find all edge cases for and have not quite managed to find them all. 

When a package is mirrored, a flag is set in the metadata that keeps track of this. However, when packages are reindexed for various reasons, sometimes the flag is not preserved.

The best work around us already been suggested: delete the mirrored packages from disk, reindex, and let Klondike mirror them again. This is a sisyphean work around... :(

**Comment by validide** [comment]
Couldn't we create 2 sub folders  in the folder were the packages are currently stored? 
Something like this:
  -  PackagesFolder
    -  Local -> all private packages go here
    -  Mirrored -> all mirrored packages go here

This way when recreating the index it would be very clear.

**Comment by chriseldredge** [comment]
Found at least one bug related to synchronizing package files with lucene index. The bug was fixed in https://github.com/themotleyfool/NuGet.Lucene/commit/6eda17b44d739dab5f50562eba9bd623ceabdfe3 and will be in the next release of Klondike.

**Comment by chriseldredge** [comment]
Released in v2.2.1

https://github.com/themotleyfool/Klondike/releases/tag/v2.1.1
