### ISSUE TITLE
Bypassing windows authentication when managing packages via nuget

### ISSUE THREAD

**Issue by ryager** [themotleyfool/Klondike#138]
During testing I disabled my ability to manage packages, which worked correctly when I used Windows Auth or my API key to push packages.  However, I could bypass this by providing the API Key of a user that was authorized to manage packages.

**Comment by chriseldredge** [comment]
This is by design. The nuget client and other clients that use API Key for authentication would not work properly if they cannot authenticate an anonymous request using the API Key request header.
