### ISSUE TITLE
Ability to see release notes

### ISSUE THREAD

**Issue by ryager** [themotleyfool/Klondike#139]
Since release notes are denoted in a NuGet package it would be nice to be able to see them when I see the package information.  It is rarely clear from the description of a new package version what the changes are and whether the risk to upgrade is acceptable.

**Comment by chriseldredge** [comment]
Added in f904b0513de1d0478426edd2f2a01dae65306d96.

**Comment by chriseldredge** [comment]
Released in v2.2.1

https://github.com/themotleyfool/Klondike/releases/tag/v2.1.1

**Comment by ryager** [comment]
Thanks Chris!  I’ll be testing out the upgrade this week.

Thanks,
Roger
