### ISSUE TITLE
Symbol loading fails

### ISSUE THREAD

**Issue by dee-see** [themotleyfool/Klondike#142]
I pushed a package and its symbols to my Klondike server and the UI confirms that symbols and sources are available for my packages. I added the http://localhost:85/api/symbols URL to my symbol loading options in VS2015.

When debugging, I get the following log in the Symbol Load Information window:

    SYMSRV:  http://localhost:85/api/symbols/TestLibrary.pdb/F42CC01CA4A645ABAFFD90245F01E4531/TestLibrary.pdb not found

Has anyone ever used this successfully with Visual Studio? Did I misconfigure?

**Comment by chriseldredge** [comment]
What version of Klondike are you using? I have used the symbol server in Klondike successfully with VS2015, but there were some bugs before 2.0 was released. Of course it is possible there are still bugs.

An access log from IIS for Klondike may help troubleshoot the problem.
