### ISSUE TITLE
Klondike indicates that there are no symbols related to package after upgrading from 1.6 to 2.0 

### ISSUE THREAD

**Issue by pvandervelde** [themotleyfool/Klondike#147]
I just upgraded our test Klondike server. The upgrade went fine and after doing a reindex I'm seeing all the packages (for as far as I can tell). However the klondike website indicates that none of the packages have symbols although some should have them. Visual studio can grab the PDBs and the source files just fine so it looks like there something wrong on the web page side. I've tried synchronizing the packages and then running another reindex but that made no difference.

**Comment by chriseldredge** [comment]
Klondike used to explode symbol packages when they're pushed, then added an option to leave source files inside the `.symbols.nupkg` file and decompress them on the fly when a debugger requests a given file. This was done to speed up pushing symbol packages and to reduce disk usage.

Klondike 2.0 removed the option to explode packages to simplify the code with a preferred behavior.

If you still have your symbol packages that were pushed before upgrading to Klondike 2.0, you could push them all again to fix the problem.

**Comment by pvandervelde** [comment]
Unfortunately I don't have those packages anymore. In hindsight we should have kept them. Oh well.
