### ISSUE TITLE
mono-service Klondike.SelfHost.exe Fails w/The server factory could not be located for the given input: Nowin

### ISSUE THREAD

**Issue by TikiBIll** [themotleyfool/Klondike#148]
First, thank you for this program. Hopefully one day Nuget.Server will work under Linux -- since you have stated you are not developing this program any longer. But until then...

When running Klondike.SelfHost.exe with --interactive, everything works fine. But when it is run with mono-service, it throws an exception (from syslog):
```
mono: bin/Klondike.SelfHost.exe: Exception has been thrown by the target of an invocation.
mono: bin/Klondike.SelfHost.exe: The server factory could not be located for the given input: Nowin
```

It seems to be related to http://stackoverflow.com/questions/1132243/msbuild-doesnt-copy-references-dlls-if-using-project-dependencies-in-solution

To work around the issue, I added a couple of lines to OnStart() in src/Klondike.SelfHost/KlondikeService.cs (right before WebApp.Start):
```
var dummyType = typeof(Nowin.ServerBuilder); //Force assembly load.
Log.Debug (m => m ("Nowin Type: {0}", dummyType.FullName));

```

This solves the problem so it can be run as a service.

On a side note, perhaps another issue to be opened, I cannot seem to find version '1.1.16' of package 'WebConfigTransformRunner'. Editing .nuget/packages.config and Ciao.targets to use version 1.0.0.1 allows me to build.

**Comment by chriseldredge** [comment]
Which version of mono and mono-service are you using?

I was able to run this on my OS X with mono installed by Homebrew:

    mono /usr/local/Cellar/mono/4.2.0.179/lib/mono/4.5/mono-service.exe Klondike.SelfHost.exe

It is possible the `mono-service.exe` you are invoking is not from Mono 4.2 or later?

I've updated the README at https://github.com/themotleyfool/Klondike/blob/master/src/Klondike.SelfHost/README.md to make the instructions more clear.

**Comment by TikiBIll** [comment]
Thanks for getting back to me.

I installed mono from the mono-project repositories, and the problem happens with both CentOS 7.2 and Ubuntu 15.10 (ostensibly running the same version of mono). Here is the CentOS 7.2 information running my "fixed" version of Klondike:

```
[bill@...... ~]$ ps ax |grep mono
 7679 ?        Sl    28:32 /usr/bin/mono /usr/lib/mono/4.5/mono-service.exe ./bin/Klondike.SelfHost.exe
29180 pts/0    S+     0:00 grep --color=auto mono
[bill@...... ~]$ /usr/bin/mono -V
Mono JIT compiler version 4.2.3 (Stable 4.2.3.4/832de4b Tue Mar 15 11:39:54 EDT 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
```

Perhaps this is a regression in mono its self?

If I'm the only one having the issue then feel free to close this bug report with no change. At least it is documented for a google search should someone else have the issue.

**Comment by chriseldredge** [comment]
I just tried running Klondike 2.0 on Ubuntu 12.04 LTS with Mono 4.2.3 and was able to start it using `mono-service`, so I'm not sure what's going sideways on your machine.

**Comment by chriseldredge** [comment]
Ah, after some more fiddling I notice your invocation is different to mine in regards to the working directory.

It seems mono-service won't load assemblies correctly if they are not in the working directory. Therefore, you should invoke `mono mono-service.exe` from the bin directory of Klondike, or use `mono mono-service.exe -d:/path/to/klondike/bin Klondike.SelfHost.exe` to set the working directory to `bin`.

I'm not sure if this behavior is well documented somewhere...

Updated README again with another caveat.

**Comment by TikiBIll** [comment]
Yes, using -d:... works. 

Thank you for your help, and this program.
