### ISSUE TITLE
Have Issue to build the klodike

### ISSUE THREAD

**Issue by nvianhd** [themotleyfool/Klondike#151]
Hi

I am new to Klondike. I can't build the FE as document here https://github.com/themotleyfool/Klondike

Here are version that installed
npm -v: 2.15.1
ember-cli@0.2.7
bower: 1.7.9

It would be nice if Klondike list of specific what version need for FE to build.  Can someone help, please?

I tried and run
npm install -g nw-gyp
npm rebuild node-sass

And I still run into issue that I can't figure out.

D:\Temp\klondike>ember build
version: 1.13.13
Build failed.
`libsass` bindings not found. Try reinstalling `node-sass`?
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (D:\Temp\klondike\node_modules\broccoli-sass\node_modules\node-sass\lib\index.js:22:11)
    at Object.<anonymous> (D:\Temp\klondike\node_modules\broccoli-sass\node_modules\node-sass\lib\index.js:188:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Temp\klondike\node_modules\broccoli-sass\index.js:5:12)
    at Module._compile (module.js:409:26)

I event tried to reinstall to run 

npm rebuild node-sass

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading 64-bit node.lib
gyp ERR! stack     at Request.<anonymous> (D:\Temp\klondike\node_modules\broccoli-sass\node_modules\node-sass\node_modules\pangyp\lib\install.js:403:20)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (D:\Temp\klondike\node_modules\broccoli-sass\node_modules\node-sass\node_modules\pangyp\node_modules\request\request.js:1255:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:419:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:309:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Temp\\klondike\\node_modules\\broccoli-sass\\node_modules\\node-sass\\node_modules\\pangyp\\bin\\node-gyp" "rebuild"
gyp ERR! cwd D:\Temp\klondike\node_modules\broccoli-sass\node_modules\node-sass
gyp ERR! node -v v4.4.4
gyp ERR! pangyp -v v2.3.3
gyp ERR! not ok
Build failed
node-sass@3.7.0 D:\Temp\klondike\node_modules\node-sass
node-sass@2.1.1 D:\Temp\klondike\node_modules\broccoli-sass\node_modules\node-sass

**Comment by chriseldredge** [comment]
I'm currently using node v0.12.2, npm 2.7.4 and bower 1.4.1 and don't have this issue.

I know my stack is quite out of date, but its working for now so I'm not inclined to upgrade anything until I need to, e.g. for an ember upgrade.
