### ISSUE TITLE
2.0 build from appveyor is missing dependencies

### ISSUE THREAD

**Issue by et1975** [themotleyfool/Klondike#153]
There's some sort of environment change resulting in `<Private />` (aka, copy local) default of a package assembly reference not being applied. You can see it in the artifact zip - Microsoft.Data.Edm is missing, for example. I've seen this before and the workaround is to override the `<Private>true</Private>` for all package references.

**Comment by chriseldredge** [comment]
The builds I've seen today contain that assembly and work fine when I try to run them. Please link to a specific build if you continue to see missing assemblies in the bin directory.
