### ISSUE TITLE
UI keeps prompting user for login information (every few seconds) 

### ISSUE THREAD

**Issue by Ashtonian** [themotleyfool/Klondike#154]
I'm having problems with the Klondike UI. Every few seconds the ui will popup the login prompt in chrome even though the password is correct and it seems to act like its logs in each time. I can navigate around and do admin things and it behaves accordingly until the prompt comes up - it seems to get in moods where it will just continuously popup every x seconds.   Its the latest version of klondike being hosted in IIS on server 2012 authenticating with kerberos (I think). 

I opened up the dev console and saw chromes annoying favicon spam events and something more interesting:

```
WebSocket connection to 'ws://redacted.internalurl.com:8083/api/signalr/connect?transport=webSockets&clientProtocol=1.4&connectionToken=redactedsomeencodedstring&connectionData=%5B%7B%22name%22%3A%22status%22%7D%5D&tid=9' failed: HTTP Authentication failed; no valid credentials available
```

I'll try on edge and see what it does.

**Comment by Ashtonian** [comment]
I tried to connect in edge and it didn't even connect - the network tab just shows a pending connection - probably something to do with the auth negotiations. 

Internet explorer and Firefox both seem fine and act accordingly. Chrome is v50.0.2661 and is the one causing problems. reading through the IIS logs yields:
```
GET /api/signalr/ping
GET /api/signalr/ping
GET /api/signalr/reconnect
``` 
the reconnect resulting in a 401

**Comment by Ashtonian** [comment]
adding the site to the local intranet settings in Internet Explorer -> Internet Options -> Security ->  Local Intranet -> Sites -> Advanced seems to have corrected it even for chrome. So I'm assuming that its something to do with the kerberos negotiations?

**Comment by chriseldredge** [comment]
Sounds like it. Klondike tries to be somewhat agnostic about authentication, since IIS and asp.net let the administrator plug in and configure their own. Some combinations seem to work better than others.

**Comment by Ashtonian** [comment]
Yep seems that it resolved the issue. I'll go ahead and close this ticket out - thanks.
