### ISSUE TITLE
Internal Server Error when pushing package with empty description.

### ISSUE THREAD

**Issue by BADF00D** [themotleyfool/Klondike#158]
Hi,
I'm creating a nuget package with fake, where the assembly attribute description is "". This results in an internal server error 500. Unfortunately there is no further information.

The nuspec file contains an empty description tag. 

```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/10/nuspec.xsd">
  <metadata>
    <id>some id</id>
    <version>0.7.0</version>
    <title>some title</title>
    <authors>authors</authors>
    <description></description>
    <dependencies>
      <dependency id="some id 2" version="0.7.0" />
      <dependency id="some id 3" version="0.7.0" />
    </dependencies>
  </metadata>
</package>
```

Within the [nuget ](https://docs.nuget.org/create/nuspec-reference) specification, I cannot find a hint that the specification tag has to be filled, so I assume this behavior is an error. If it is not, it would be great if there error is a little more verbose.

Best Greetings

**Comment by chriseldredge** [comment]
Please look in `~/App_Data/Logs/Klondike.log` for details on what went wrong. You can also try enabling [showExceptionDetails](https://github.com/themotleyfool/Klondike/blob/master/src/Klondike.WebHost/Settings.config#L118) in Settings.config, but it won't mean that the NuGet client will show anything useful.

**Comment by inosik** [comment]
The required fields in a `.nuspec` are `id`, `version`, `authors` and `description`. These attributes are written in **bold** font on the page @BADF00D linked. I agree that this should be stated more clearly in the documentation.

Do you use Paket to create your packages, @BADF00D? I had this problem with Paket, and tried to reproduce with NuGet, but it refuses to pack a `.nuspec` with any of the required fields missing or beeing an empty string.

**Comment by BADF00D** [comment]
Yes, I used paket to create the nuget package. So I should forward this error to them?

**Comment by inosik** [comment]
Please leave a comment on fsprojects/Paket#1831, @BADF00D. Thanks.
