### ISSUE TITLE
IsLatestVersion no longer being updated when publishing new package

### ISSUE THREAD

**Issue by smadam813** [themotleyfool/Klondike#159]
I am currently using Klondike version 2.1.1.

Whenever I publish a new package to our repository, the IsLatestVersion field no longer turns to true, but it does change it on the previous package to false.

**Comment by smadam813** [comment]
Logs for packages that no longer has IsLatestVersion as true on any package:
```
INFO   73 Audit MoveNext Add package Chatham.Blah.SomeLibrary version 2016.720.22 requested by ChathamPackageManager
INFO   73 LucenePackageRepository MoveFileWithOverwrite Moving package file from C:\Klondike\App_Data\Packages\.tmp\package-a88a4b2a-2819-48c8-af1f-977168415200.nupkg.tmp to C:\Klondike\App_Data\Packages\Chatham.Blah.SomeLibrary.2016.720.22.nupkg.
INFO   73 LucenePackageRepository MoveNext Indexing package Chatham.Blah.SomeLibrary 2016.720.22
INFO   50 PackageFileSystemWatcher MoveNext Indexing modified package C:\Klondike\App_Data\Packages\Chatham.Blah.SomeLibrary.2016.720.22.nupkg
```

**Comment by chriseldredge** [comment]
I'm unable to reproduce this problem. Can you reproduce it with publicly available packages, like something from nuget.org?

My instance is running 2.1.1 and setting this metadata correctly as far as I can tell.

Please provide more specific instructions.

**Comment by smadam813** [comment]
We have 65000+ packages (Not Unique Packages) and push each nuget package with our TeamCity instance.  Unfortunately I am unable to tell you anymore than that.  This is a strange behavior and was unable to detect anything within push logs or Klondike logs.

**Comment by chriseldredge** [comment]
Can you elaborate on where you are seeing this behavior? In the browser? In Visual Studio?

On one of my instances, I have 380 versions of a unique package ID, and I have exactly one that has `IsLatestVersion = true`.

    curl 'klondike.example.com/api/odata/Packages?$filter=Id+eq+%27SamplePackage%27&$inlinecount=allPages&$top=1'

Returns response with `odata.count: 380`.

    curl 'klondike.example.com/api/odata/Packages?$filter=Id+eq+%27SamplePackage%27+and+IsLatestVersion&$inlinecount=allPages'

Returns response with `odata.count: 1`

**Comment by smadam813** [comment]
Running the first query returns "odata.count":"190"
Running the second query returns "odata.count":"0"

If I re-index all packages, the second query changes to "odata.count":"1"

After a few nuget publishes from our teamcity server, the package eventually reads 0 again.  The previous version that had IsLatestVersion set to true becomes false (supposed to happen), but the new published package IsLatestVersion equals false as well and never is updated to true.  I have no idea what is causing this, but I know it doesn't happen on every publish.  What I can tell you is since we have so many packages, multiple are affected within the hour since we are constantly publishing new packages.  Once IsLatestVersion count is 0 (all IsLatestVersion is false), the package will remain this way until a re-index.

We use IsLatestVersion in a lot of our scripts, so this has forced us to stay on the old version.  Also the Visual Studio functionality is very strange as I reported in the other issue.  (VS defaults to showing older versions rather than latest when browsing)

**Comment by chriseldredge** [comment]
Answering these questions may help narrow down the problem:

1. Is it common for you to push pre-release packages?
2. Do you often push packages that are not the latest version at the time they're published?
3. Do you ever overwrite a previously published package version?
4. Do you often delete previously published packages?

**Comment by smadam813** [comment]
Is it common for you to push pre-release packages?
**We never push pre-release packages**

Do you often push packages that are not the latest version at the time they're published?
**Every time a library builds, we push it.  We always push packages that are the latest version at the time they're published.**

Do you ever overwrite a previously published package version?
**We never overwrite published package versions as TeamCity increments each version pushed.**

Do you often delete previously published packages?
**We do delete previously published packages for multiple reasons.**

1. Deprecation of a Library
2. Removing very old packages that are no longer used
3. Package was created by accident or improperly named

**Comment by chriseldredge** [comment]
I'm unable to reproduce this issue and haven't heard of other users encountering it. Feel free to reopen if you are able to provide detailed instructions to reliably reproduce the problem.
