### ISSUE TITLE
Visual Studio 2015 defaults to installing oldest version of package instead of latest

### ISSUE THREAD

**Issue by smadam813** [themotleyfool/Klondike#160]
I am currently using Klondike version 2.1.1.

Not sure why, but this specific functionality has changed after upgrading to 2.1.1.

**Comment by chriseldredge** [comment]
This is a problem related to narrowing search by target framework version. The problem of returning a unique package ID that supports a target framework version is pretty tricky to solve. On top of this, the Visual Studio client typically filters packages with `IsLatestVersion` or `IsAbsoluteLatestVersion`. This can lead to incorrect results if a given package had support for, e.g. net35, but dropped it in their latest releases.

Klondike attempted to solve this problem by returning non-unique results and letting the client deal with it. That worked ok on VS 2013, but stopped working.

I've noticed that NuGet Gallery simply ignores the target framework filter and returns garbage results no matter what. I guess I'll change Klondike to return garbage too.
