### ISSUE TITLE
Setup server with user authentication

### ISSUE THREAD

**Issue by FreeFrags** [themotleyfool/Klondike#162]
Hi, 

I was wondering if it is possible to setup a server which is secured not only for publishing packages but also for browsing and downloading them.

How would you set up a server this way?

Thanks in advance

**Comment by chriseldredge** [comment]
When hosting in IIS, you can use IIS Manager or another tool to enable/disable various authentication modes like anonymous, basic and NTLM.

When using the self-hosted Klondike, try `--enableAnonymousAuthentication=false` and `--enableIntegratedWindowsAuthentication=true`.

See https://github.com/themotleyfool/Klondike/blob/master/src/Klondike.SelfHost/README.md
