### ISSUE TITLE
VS 2015 with new targetframeworks (ex 452) will not bring back any 45 targeted packages

### ISSUE THREAD

**Issue by timritzer** [themotleyfool/Klondike#166]
Despite being perfectly compatible, VS 2015 returns no nuget packages when querying for project set to target 452. All packages are 45.

Any way to disable the targetframework filtering? I am having to access them through the file share to make this work. Would love to simply not filter since it can't be intelligent about backwards compatibility on searches.

/api/odata/Search()?&searchTerm=%27%27&targetFramework=%27net452%27&includePrerelease=false&$skip=0&$top=26

Does not work, but if I manually change it to

/api/odata/Search()?&searchTerm=%27%27&targetFramework=%27net45%27&includePrerelease=false&$skip=0&$top=26

it works great.

**Comment by chriseldredge** [comment]
While net452 is largely the same as net45, it is not accurate to say they are "perfectly compatible".

For example, [HostingEnvironment.QueueBackgroundWorkItem](https://msdn.microsoft.com/en-us/library/dn636893(v=vs.110).aspx) was added in net452, and any code that attempts to use that method will result in a runtime error if running on net45 or net451.

Anyway, the public feed on nuget.org appears to completely ignore the targetFramework filtering, so maybe Klondike should follow suit and joyfully offer packages that might not be compatible.

The direction they seem to be going in is letting the client decide at install time if a package is compatible or not.

**Comment by chriseldredge** [comment]
#160 is a related issue that would be addressed by changing Klondike's behavior to ignore the targetFramework filter.

**Comment by timritzer** [comment]
Fair, I really meant more that 452 can safely use any 45 libraries then that they were identical.

A proper version filter would have to take into account all compatibility with previous versions. Which as a developer sounds really difficult. :-) I support simply not supporting the filter right now.

**Comment by chriseldredge** [comment]
On my instance, I get results for packages that target net45 when I search for net452, so I don't know why that isn't working for you.

Regardless, I'll probably disable the filtering in the next release.

**Comment by timritzer** [comment]
Ok, awesome. I worked around it on my end, so it isn't blocking me anymore. Thanks for the prompt and helpful conversation!
