### ISSUE TITLE
Klondike Self-Host Release no x64 release

### ISSUE THREAD

**Issue by tmulkern** [themotleyfool/Klondike#172]
Would it be possible to have an AppVeyor Build that build a 64bit Release.

**Comment by chriseldredge** [comment]
I believe all assemblies are platform independent so I'm not clear on what specifically is required here? Is it a matter of putting something in App.config to prefer 64-bit runtime?

**Comment by tmulkern** [comment]
I believe the problem is that the "Prefer 32bit Flag" is set in the Build Options for the Klondike.SelfHost project. I have created a pull request to fix it #173

**Comment by tmulkern** [comment]
Fixed with pull request #173
