### ISSUE TITLE
Basic authentication for web UI on Linux

### ISSUE THREAD

**Issue by reyalpsirc** [themotleyfool/Klondike#179]
I'm running Klondike.SelfHost.exe on Ubuntu and it is working fine but, I need to make this server private so that only people with an username and password can access its web interface and such. I read that this supports Basic Auth but, can you give me a bit more info about how to do it or what to search for on the web in order to use Klondike.SelfHost.exe with Basic Auth?

**Comment by chriseldredge** [comment]
Mono's self hosting support does not support authentication schemes other than anonymous as far as I know. One option would be to configure Klondike to only listen on localhost and use apache with mod_proxy, nginx, or another reverse proxy that enforces authentication and authorization.

**Comment by reyalpsirc** [comment]
I tried that with nginx but it's giving the following error:

	at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContextStage.BeginEvent (System.Object sender, System.EventArgs e, System.AsyncCallback cb, System.Object extradata) [0x0001f] in <392be445bb6947f2a5f768f7860b8204>:0 
	  at System.Web.HttpApplication+<RunHooks>c__Iterator0.MoveNext () [0x000d2] in <79d7580b4e46487286a5f8386a98413d>:0 
	  at System.Web.HttpApplication+<Pipeline>c__Iterator1.MoveNext () [0x00577] in <79d7580b4e46487286a5f8386a98413d>:0 
	  at System.Web.HttpApplication.Tick () [0x00000] in <79d7580b4e46487286a5f8386a98413d>:0 

My nginx configuration is simple:

	worker_processes  1;

	events {
	    worker_connections  1024;
	}

	http {
	  server {
	    listen 8081;

	    auth_basic "Logirix Nuget Server";
	    auth_basic_user_file passwords;

	    location / {
	      proxy_pass http://localhost:9000;
	    }
	  }
	}

Any idea why it doesn't work? In fact, I can see the page for some time but, as soon as I click on the Api tab, it doesn't work anymore...

**Comment by chriseldredge** [comment]
You see that error in the browser or in Klondike's log file?

**Comment by reyalpsirc** [comment]
This happens in the browser and if I do a curl with the ApiKey an Basic Auth data to the 8081 port

**Comment by chriseldredge** [comment]
Can you check in Klondike's `App_Settings/Logs` folder for more info? That stack trace doesn't have much context to understand what is happening.

**Comment by reyalpsirc** [comment]
I don't have a folder called `App_Settings`. Did you mean `App_Data`?

This is what my Klondike-Release folder (which was cloned from git) has:

<img width="499" alt="captura de ecra 2016-11-17 as 20 53 27" src="https://cloud.githubusercontent.com/assets/5243311/20407148/00f173ac-ad08-11e6-8af2-d21c0ce6d2fd.png">

And this is the content of `App_Data\Logs\Klondike.log`:

	2016-11-17 19:13:45,083 INFO   Threadpool worker LucenePackageRepository UpdatePackageCount Refreshing index. Package count: 1
	2016-11-17 19:15:36,377 INFO   Threadpool worker LucenePackageRepository UpdatePackageCount Refreshing index. Package count: 1
	2016-11-17 19:17:08,140 INFO   Threadpool worker LucenePackageRepository UpdatePackageCount Refreshing index. Package count: 1
	2016-11-17 19:18:24,295 INFO   Threadpool worker LucenePackageRepository UpdatePackageCount Refreshing index. Package count: 1
	2016-11-17 19:21:50,684 INFO   Threadpool worker LucenePackageRepository UpdatePackageCount Refreshing index. Package count: 1
	2016-11-17 19:25:43,107 INFO   Threadpool worker LucenePackageRepository UpdatePackageCount Refreshing index. Package count: 1
	2016-11-17 19:34:30,020 INFO   Threadpool worker LucenePackageRepository UpdatePackageCount Refreshing index. Package count: 1
	2016-11-17 20:52:18,011 INFO   Threadpool worker LucenePackageRepository UpdatePackageCount Refreshing index. Package count: 1

**Comment by reyalpsirc** [comment]
Ok, I had a problem on my Settings.config file and I restored it. Anyway, I can only start this if I run in interactive mode:

`sudo mono ~/Klondike-Release/bin/Klondike.SelfHost.exe --interactive --port=8080`

When running as a service, this simply doesn't start

`sudo mono-service ~/Klondike-Release/bin/Klondike.SelfHost.exe --port=8080`

No output is given either. Any idea?

**Comment by chriseldredge** [comment]
There is a confusing and long standing pitfall with mono-service in which you must set the working directory to the directory containing the service exe you want to run.

In other words:
```bash
cd /path/to/Klondike-Release/bin
sudo mono-service Klondike.SelfHost.exe --port=8080
```

Otherwise the AppDomain is not configured correctly and assembly loading and other stuff will explode spectacularly.

**Comment by reyalpsirc** [comment]
Thanks, it works now! That was also the reason why my init.d script was not working 👍

**Comment by reyalpsirc** [comment]
Hmm, everything works fine except the push/delete of packages... For some reason, it keeps asking me the username and password when I set it correctly... Those credentials work everywhere except for pushing/deleting the nugets... Any idea about the reason? Because right now I managed this only by disable basic auth on `api/packages`

**Comment by chriseldredge** [comment]
You are using an api key that has package manager permission? If so, I don't know. You could also try [allowAnonymousPackageChanges](https://github.com/themotleyfool/Klondike/blob/master/src/Klondike.WebHost/Settings.config#L21) to `true`.

**Comment by reyalpsirc** [comment]
That didn't work also... I found out that its a bug either on NuGet.exe or Mono running it. 

Whenever I make a push or delete, Wireshark shows me that for the `push`, only the username is sent (password was blank). If I use `nuget sources add` the password is indeed sent but then I get an `500 Internal Server Error` related to and empty stream.

Regarding the `delete`, Wireshark simply shows me that no matter what I add on sources or the input I give for username/password, nothing is sent at all to the auth basic header...

The solution was to change the nginx.conf file so that I can protected this except for Non GET request made for /api/packages:

    worker_processes  1;

    events {
        worker_connections  1024;
    }

    http {
      server {
        listen 8081;

        auth_basic "Logirix Nuget Server";
        auth_basic_user_file passwords;

        location / {
          proxy_pass http://localhost:8080;
        }

        location /api/packages {
          limit_except GET { 
            auth_basic off;
          }
          proxy_pass http://localhost:8080/api/packages;
        }
      }
    }

Do you if this might have any impact on something else or if I should also protect something else regarding the /api/packages/?

**Comment by reyalpsirc** [comment]
Can this cause problems with mirroring of dependencies? Because when I try to install package, it simply fails with connection refused.

Am I doing something wrong or is it related to this authentication thing?
