### ISSUE TITLE
Search on /api/odata returns urls with localhost

### ISSUE THREAD

**Issue by reyalpsirc** [themotleyfool/Klondike#181]
When I try to install a package from my Klondike server, it simply fails because the response from queries with `/api/odata/Search()?$filter=IsLatestVersion&searchTerm=...` return results like this below

    [...]
    <link
        rel="self"
        href="http://localhost:8080/api/odata/Packages"/>
        <entry>
            <id>
                http://localhost:8080/api/odata/Packages(Id='MyPackage',Version='1.0.0')
                </id>
            <category
                term="NuGet.Lucene.Web.Models.ODataPackage"
                scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme"/>
            <link
                rel="edit"
                href="http://localhost:8080/api/odata/Packages(Id='MyPackage',Version='1.0.0')"/>
    [...]

Since I'm using nginx to proxy `http://localhost:8080`, how can I configure Klondike to point `http://localhost:8080` links to `http://IP_ADDRESS:9000` ?

**Comment by chriseldredge** [comment]
I haven't set up a reverse proxy with Klondike before, but is there a way to customize the `Host` header that nginx sends to Klondike? This would probably be the easiest way to control how Klondike generates absolute URIs.

**Comment by reyalpsirc** [comment]
Ah! That solved it. If anyone gets this problem, here's the solution for the nginx.conf file:

    worker_processes  1;

    events {
        worker_connections  1024;
    }

    http {
      server {
        listen 9000;

        auth_basic "My Server";
        auth_basic_user_file passwords;

        location / {
          proxy_set_header Host IP_ADDRESS:9000;
          proxy_pass http://localhost:8080;
        }

        location /api/packages {
          limit_except GET { 
            auth_basic off;
          }
          proxy_set_header Host IP_ADDRESS:9000;
          proxy_pass http://localhost:8080/api/packages;
        }
      }
    }
