### ISSUE TITLE
Klondike SelfHost.exe now stops after starting

### ISSUE THREAD

**Issue by eeevans** [themotleyfool/Klondike#187]
Running Klondike 2.1.1 since Jan 17 successfully.  On Feb. 22 it would stop immediately after starting.  No error messages in event log nor Klondike.log.  Half way through the log it stops saying listening on port 8080.  Subsequent logs are like the last half of this one. 

Not sure how to troubleshoot from here.  

Here is a link to the gist of the Klondike log from 2/22. [https://gist.github.com/eeevans/9b8d37ffaf7c29b5e72d16bf1ab37644#file-klondike-log-2017-02-22](https://gist.github.com/eeevans/9b8d37ffaf7c29b5e72d16bf1ab37644#file-klondike-log-2017-02-22)

It runs interactively but not as a service.  I have tried running it as Local Service, Network Service, and as a Domain account that it successfully runs interactively as but it will not continue running.

**Comment by Dids** [comment]
@eeevans Did you ever figure this out? I'm seeing the same issue when running on Docker Cloud.
I previously ran it on a custom Rancher server successfully, but right now it's acting like something's sending an "enter" input to it immediately after it has started.

**Comment by eeevans** [comment]
No, I was going to try and debug it with wind gusts but not sure how

**Comment by chriseldredge** [comment]
Is there a link to the wrapper script that is running Klondike within Docker? I've seen scripts that attempt to control Klondike via standard input. It might be that something is going wrong there and Klondike is interpreting that as a shutdown signal.

**Comment by Dids** [comment]
@chriseldredge In my case I was using a variation of this: https://github.com/athieriot/docker-klondike

I'm building one from scratch right now, just to see if I can replicate it. It's very weird that it works locally though.

**Comment by chriseldredge** [comment]
My best guess is that stdin is being closed or wired up to something that causes "interactive" mode in Klondike to think that enter has been pressed. Might be possible to redirect stdin in the Dockerfile to some device or file descriptor that never closes and never produces any input.

**Comment by Dids** [comment]
I did try setting `stdin_open: false`, but that didn't make a difference. Additionally, running Klondike in background (eg. with `<command >&`) still caused it to immediately trigger the shutdown.

**Comment by chriseldredge** [comment]
You'd need to redirect stdin to something like a fifo. I have an old example gist (https://gist.github.com/chriseldredge/37d41925fdddecea8517) that does something similar but for an old beta from when .net core was KRuntime. It uses `mkfifo` to accomplish something similar.

**Comment by Dids** [comment]
I think you're on to something, because if I do `<klondike> < /dev/null` it's also shutting down immediately locally (where it works otherwise), so it's (probably) not really waiting for "enter" per se.

**Comment by chriseldredge** [comment]
Correct. Klondike depends on `Console.ReadLine()` to block. If stdin is closed, it will return immediately. If enter is pressed, the blocking resumes. Both have the same effect.

**Comment by Dids** [comment]
I'm happy to report that faking standard input with FIFO worked absolutely great, both locally and on Docker Cloud. :)

**Comment by eeevans** [comment]
I was able to fix it by deleting the service registration and recreating it.

**Comment by eeevans** [comment]
Did you run it as a service in Docker?
