### ISSUE TITLE
Service performance under load

### ISSUE THREAD

**Issue by benetnash** [themotleyfool/Klondike#39]
Hi!
I just set up Klondike as drop in replacement for default nuget service and with default settings performance is lower then default instance. I have almost 4000 packages in repository. Push of new version takes between 5 to 60s on unused service, but when build agent is performing nuget update in the same time push times out. Is there any way to tune this?
 
Performance under high load of old service could be increased with web gardens, but probably this would crash lucene in Klondike.  

Also unfortunately I'm unable to show any configs from this service.

Regards

**Comment by chriseldredge** [comment]
Many improvements to indexing and search performance have landed in master. I'm going to close this issue, but if you continue to experience poor performance feel free to open another issue.
