### ISSUE TITLE
Comprehensive installation instructions?

### ISSUE THREAD

**Issue by nathan-alden** [themotleyfool/Klondike#45]
The README is not very comprehensive when it comes to installing Klondike with the release package. Are there step-by-step instructions somewhere for getting Klondike running, assuming a fresh installation of Windows Server (for example)? I am having trouble filling in the blanks (or even getting started, really).

I have IIS installed, .NET 2.0 to 4.5.2 installed, and MSBuild 12.

**Comment by webframp** [comment]
* Edit the web.config adjusting appSettings as desired

Is there perhaps more info on the possible settings for these?

**Comment by chriseldredge** [comment]
There are comments inline with the settings in [Web.config](https://github.com/themotleyfool/Klondike/blob/master/app/Web.config) on master.

The [self-host](https://github.com/themotleyfool/Klondike/tree/self-host) branch is the current branch of active development for the next release. The README on this branch has more details about deploying Klondike and building it from source.

**Comment by chriseldredge** [comment]
The README in master now has more comprehensive set up instructions. Please note I haven't made an official release yet, so these instructions apply to recent AppVeyor builds or builds from source for the time being.

**Comment by jhurdlow** [comment]
I can't find any info on how to set passwords in the readme (or anywhere else). Can't "Sign In" without a password, but there doesn't appear to be any way to set one. Also, will WindowsAuth be coming to the IIS hosted version?

**Comment by chriseldredge** [comment]
Updated the README to add some notes on authentication. Windows auth is already supported in IIS hosted version. You enable it in IIS Manager with Basic/NTLM authentication modules.

**Comment by penartur** [comment]
I followed the instructions, yet it does not work; requests to `/api/` return 404. It is as if the application itself did not start, and did not set up the routes, so that only static files (e.g. `index.html`) are served.

Looking in the [Web.config](https://github.com/themotleyfool/Klondike-Release/blob/master/Web.config), I don't see any entry point. How is IIS supposed to start up the application (or anything at all)? Maybe I'm missing something?

**Comment by chriseldredge** [comment]
@penartur Please open a new issue with more information, including what version of Klondike you are using, what version of IIS, and the contents of `~/App_Data/Logs/Klondike.log`.

**Comment by penartur** [comment]
@chriseldredge Never mind, it is just that ASP.NET wasn't completely installed on that machine.
(`Logs` folder, obviously, was empty)
