### ISSUE TITLE
handling vNext packages

### ISSUE THREAD

**Issue by chriseldredge** [themotleyfool/Klondike#52]
vNext packages may contain some files in src and also include PDB symbols which causes Klondike to handle them as symbol packages. They should be handled as normal packages.

**Comment by chriseldredge** [comment]
Example vNext package that looks like a symbol package but is not:

[Nowin.vNext](https://ci.appveyor.com/nuget/nowin-vnext-po3h1go8uenn/api/v2/package/nowin.vnext/0.1-beta1-t141018001204) (binary data).

**Comment by chriseldredge** [comment]
Currently packages pushed to `/api/packages` that contain symbols will be treated as symbol packages. This behavior will change in future releases.

**Comment by smudge202** [comment]
The `dotnet` moniker appears to cause an Internal Server error (somewhat relates to this old issue).

**Comment by chriseldredge** [comment]
What version of Klondike? Do you have a stack trace from `~/App_Data/Logs/Klondike.log`?

**Comment by smudge202** [comment]
I'll grab it for you tomorrow or Thursday. If it's easier, I can point you to the github project I was trying to publish to Klondike?

**Comment by chriseldredge** [comment]
Either way. But what version of Klondike are you using?

**Comment by jarroda** [comment]
Has their been any progress on this issue?  We would love to use klondike as a nuget cache, but issues with newer (net core) packages seem to be making that impossible right now.

**Comment by chriseldredge** [comment]
Last time I tested, Klondike worked reasonably well with vNext packages. If you are aware of specific issues, please open a new issue for them.

The particular problem reported by @smudge202 has been resolved as far as I am aware.
