### ISSUE TITLE
Content negotiation not working on mono

### ISSUE THREAD

**Issue by chriseldredge** [themotleyfool/Klondike#55]
Mono 3.8.0 fails to correctly parse Accept headers such as `Accept: text/html;q=0.9,*/*;q=0.8` resulting in content negotiation failing and the first formatter (json) being used. This prevents the API Documentation explorer from showing html in the browser.

**Comment by chriseldredge** [comment]
Fixed in mono 4.2.0.

**Comment by llehn** [comment]
I'm on mono 4.2.3 and I'm experiencing the problem with missing content-type:

Example: request to /packages/list returns a response without content-type, i.e. it's not being rendered as html.

**Comment by chriseldredge** [comment]
Can you provide a complete example? For instance, using `curl -i http://example.com/packages/list`...
