### ISSUE TITLE
Search should match partial package ID with dot separator

### ISSUE THREAD

**Issue by smadam813** [themotleyfool/Klondike#57]
I have tried escaping the periods thinking maybe it was something with the query it was making to Klondike, but no luck.  I have package names such as "Company.Foo.Bar" and I cannot search specifically for it.  Instead I will need to search for "Company Foo" and scroll through the list to find the package.  I will be looking through the source to see if I can figure this out, but wanted to raise this as an issue.

**Comment by chriseldredge** [comment]
Please try build 81 or higher and see if the search results match your expectations.

https://ci.appveyor.com/project/chriseldredge/klondike/build/81/artifacts

You should rebuild your index on the Admin screen to make sure the new analyzers take effect.

**Comment by smadam813** [comment]
The new build works great so far.  It has fixed many of the issues I was describing before.  Another way to ensure the search returned exactly what was expected was to add a * at the beginning and end of what was being searched for.  Thank You Chris, Klondike is a really awesome tool!
