### ISSUE TITLE
Prerelease versions followed by dash ("-")

### ISSUE THREAD

**Issue by fgauthier-boutin** [themotleyfool/Klondike#62]
Hi there,
I'm actually facing an issue when I try to push a package with prerelease versionning info (see http://docs.nuget.org/docs/reference/versioning) on my Klondike server instance.

Here is the sequence to reproduce the issue:
- Create an HelloWorld project with this nuspec info
```
    <package >
      <metadata>
        <id>HelloWorld</id>
        <version>1.0.0-alpha</version>
    ...
```
- Pack and push on klondike with nuget.exe (I did it anonymously). No problem so far, you should receive a "Your package was pushed." message.

- If you go to your Klondike server front-page and try to find the HelloWorld package you are NOT able to find it.

I tried to locate the package through the Visual Studio's Manage Nuget Packages window, but I cannot see HelloWorld.

BUT 

If you try a simple:

nuget install HelloWorld /version 1.0.0-alpha /source klondike

It works!

Thank you,

**Comment by chriseldredge** [comment]
The latest AppVeyor builds include a filter that allows you to show prerelease packages in the package list and search results.
