### ISSUE TITLE
Admin role can't manage accounts

### ISSUE THREAD

**Issue by dwarburt** [themotleyfool/Klondike#63]
On a new install from the v1.6.2 release, using the unmodified config, when I pull up the site from the desktop of the server (http://127.0.0.1/), it _does_ log me in as LocalAdministrator, and there is an "Admin" link on the top left, but after clicking that the first page says "You are not allowed to synchronize packages.".  There is a link to Manage accounts, but that page says: "You are not allowed to modify accounts."

**Comment by chriseldredge** [comment]
Did you make any changes to Web.config? Have you enabled Windows Authentication or any other IIS based authentication modules?

**Comment by dwarburt** [comment]
In web.config I changed localAdministratorApiKey to match what we were using with Nuget.Server and set EnablePackageFileWatcher to true, but that's it, everything else is "as is".  As far as authentication, it's set to Anonymous Authentication (enabled) and everything else disabled.

One other thing I've noticed is that on the /profile page it says "You have the following permissions: AccountAdministrator PackageManager".

**Comment by chriseldredge** [comment]
I wonder if a hard refresh would make the Admin page allow you to perform these administrative actions. There could be a race when the app first starts up as the server is creating the LocalAdministrator account at the same time that the front-end app is probing for your authentication settings.

**Comment by dwarburt** [comment]
hm, i did clear localStorage & cookies once to get the api key to display correctly after I changed it in web.config, but this problem is still ongoing.  I just tried again now and same result.  I've tried to debug it a little but haven't seen EmberJS before.  I found the userPermissionObserver mixin, and the list.hbs where it's checked, but haven't found the part that queries the server for the permissions.

**Comment by chriseldredge** [comment]
Change the location to `your-domain.com/api`, scroll down to the `Synchronize` API method and click the submit button. Does that work?

Alternatively, does this work?

    curl -H "X-NuGet-ApiKey: xyz" -d '' http://your-domain.com/api/indexing/synchronize

**Comment by dwarburt** [comment]
yes, that works

**Comment by chriseldredge** [comment]
In that case the bug is most likely in the Ember front-end. Since I'm working on a new release, I'll probably close this as wont-fix and hopefully things will be better on the newer version.
