### ISSUE TITLE
Requiring authentication for read-access (windows authentication)

### ISSUE THREAD

**Issue by farhanalam** [themotleyfool/Klondike#66]
Is there a way to prevent anonymous users read access to the packages when Windows authentication is enabled? 

We followed the solution [here] (https://github.com/themotleyfool/Klondike/issues/43#issuecomment-41397230), but we need all requests to be authenticated.

**Comment by chriseldredge** [comment]
You could try disabling Anonymous Authentication and that should do the trick. Alternatively, requiring all users to be in a certain role can be achieved by adding an entry to your Web.config like this example:

```xml
<system.web>
  <authorization>
    <allow roles="KlondikeUsers" />
    <deny users="*" />
   </authorization>
</system.web>
```

**Comment by farhanalam** [comment]
Thanks for the response. I should have been more clear earlier. 

If I disable anonymous authentication, I get stuck on a 401 authentication challenge.

I noticed in wireshark that the request is authenticating successfully to /api/, at which point the server initiates an HTTP 307 temporary redirect to /api/odata. It is at /api/odata that I am unable to authenticate (even though the Authentication headers are set). Going directly to /api/odata via the browser produces the same results 

IIS Configuration: 
Windows authentication enabled 
Basic authentication enabled
Anonymous disabled.

**Comment by farhanalam** [comment]
I believe I've discovered why I am being prompted, though I don't have a permanent solution.

The prompt appears only when I specify values in PackageManager and/or AccountAdministrator fields (web.config). For now, we are manually giving these permissions via the UI.

**Comment by chriseldredge** [comment]
I need to do some testing of my own. For my understanding, you are using Active Directory authentication and it doesn't allow you to log in for read access when you use the role mappings?

**Comment by farhanalam** [comment]
Yes, that is correct.

**Comment by chriseldredge** [comment]
I think I found the problem that the middleware for Api Key authentication was not running in the right stage in IIS's integrated pipeline.

This should be fixed in NuGet.Lucene by https://github.com/themotleyfool/NuGet.Lucene/commit/87117d624be6c85be79115202fa18ebcc9ba0770.

I upgraded the packages in Klondike in commit 979c3e0d23094730906123da66c9ce5b9c55bcb3.

Please try the new build from AppVeyor and let me know how it goes:
https://ci.appveyor.com/project/chriseldredge/klondike/build/75/artifacts

**Comment by farhanalam** [comment]
Thank you. It works. However, I had to set the package feed to /odata before VS picked it up

**Comment by chriseldredge** [comment]
I found in the master branches that `/api/` was not being redirected to `/api/odata` for NuGet user agents. I added a redirect for this URL. It'll show up in the next build.
