### ISSUE TITLE
Klondike.SelfHost.exe missing from 1.6.2

### ISSUE THREAD

**Issue by thesecmaestro** [themotleyfool/Klondike#67]
Instructions on the website indicate Klondike.Selfhost.exe in binary package.
Installed package but cannot find .exe file.

https://github.com/themotleyfool/Klondike#self-hosted-klondike:

The binary release also includes Klondike.SelfHost.exe in the bin directory. It can be run from the console using mono or the .net framework:

**Comment by chriseldredge** [comment]
The latest branch including the self-hosted executable have not been released. I added some links to the readme that point to AppVeyor builds you can download and try out in the mean time.

For example, here's the latest build: https://ci.appveyor.com/project/chriseldredge/klondike/build/72/artifacts
