### ISSUE TITLE
Multiple packageMirrorTargetUrl

### ISSUE THREAD

**Issue by drphrozen** [themotleyfool/Klondike#68]
It would be nice if it was possible to have multiple `NuGet.Lucene.Web:packageMirrorTargetUrl`.

**Comment by chriseldredge** [comment]
I agree, but I'm not going to be able to work on this any time soon. I'll leave it open as a feature request for future releases.

**Comment by chriseldredge** [comment]
Added in https://github.com/themotleyfool/NuGet.Lucene/pull/28, available in build 81.

**Comment by drphrozen** [comment]
Cool thx :+1:
