### ISSUE TITLE
odata $filter by Package Id and IsLatestVersion cannot return versions higher than 99

### ISSUE THREAD

**Issue by dankarmy** [themotleyfool/Klondike#69]
I've just installed Klondike and moved over approx. 1,600 private nugget packages to Klondike from a standard Nuget.Server installation.

When using odata to query the packages there is some bizarre behaviour that i'm not expecting to see.We have a few packages where the revision is over .99 (e.g. 1.0.0.248). When querying with odata it refuses to return any package where the revision is over .99.

Using the same odata query on a standard Nuget.Server installation returns all versions right up to the .248 revision as expected.

Here is the query:

Packages()?$filter=Id eq 'IdOfThePackage'

**Comment by dankarmy** [comment]
Looking at the Klondike.log I can see the packages higher than .99 in question is successfully installed:

2015-02-03 17:44:53,155 INFO   43 LucenePackageRepository MoveNext Adding package 84d71555-370f-41c0-a680-dbe5901294f0 1.0.0.165 to file system
2015-02-03 17:44:53,176 INFO   43 LucenePackageRepository MoveNext Indexing package 84d71555-370f-41c0-a680-dbe5901294f0 1.0.0.165

**Comment by dankarmy** [comment]
Additionally, there also appears to be a bug with versioning and ordering when querying with odata and paging.

Packages()?$filter=Id eq 'IdOfThePackage'

On page one I get

1.0.0.0
through
1.0.0.39

Page two:

1.0.0.4
through
1.0.0.73

Page three:

1.0.0.8
through
1.0.0.99

etc.

With nothing over 99 listed.

**Comment by chriseldredge** [comment]
Which version of Klondike are you using? (It should be visible in the footer on the web app.)

**Comment by dankarmy** [comment]
I wasn't able to get the front end working correctly under windows on IIS.

I downloaded the master from 03/02 though.

**Comment by dankarmy** [comment]
Any update on this issue I've reported - I am unable to use Klondike currently due to this bug. Do you have a workaround?

**Comment by chriseldredge** [comment]
I need to generate a bunch of packages to test and reproduce this issue.

**Comment by chriseldredge** [comment]
I generated 250 dummy packages with same ID and versions ranging from 1.0.0.0 to 1.0.0.250. I can confirm that `nuget list -allversions` returns all 250 packages, but not sorted by version so they appear out of order.

`nuget list` without the `-allversions` flag does show me the highest version of the package.

Adding `$orderby=Id,Version` to the OData query params seems to fix the issue, though `nuget list` should also result in a sorted list of packages.

It is possible that there are multiple bugs, but the only one I can confirm right now is that the default sorting for OData should be Id,Version.

**Comment by dankarmy** [comment]
thanks for the info.

I can confirm that if I pass the $orderby=Id,Version to the odata query it does indeed fix the issue.

I was using Nuget.PackageRepositoryFactory to create an instance of a IPackageRepository to query the Packages, but because this seems to be hard coded to produce an odata query which doesn't include any ordering, the packages are returned out of order (and partially returned - I only get some of all my packages back in the collection when calling FindPackages(id[]))

I *think* this is caused by the next link at the bottom of the XML data returned by the odata query (which includes a $skip directive).

Because of these bugs and trying to use Nuget.PackageRespostoryFactory, I've ripped this out and using an odata proxy class generated by visual studio to do the querying which has resolved my issues for now anyway (provided I use the order by Package.Id, Package.Version).

**Comment by chriseldredge** [comment]
Stable ordering should be ensured by WebApi OData in recent builds. Please try a new AppVeyor build and let me know how it goes.
