### ISSUE TITLE
Unable to access the log in link

### ISSUE THREAD

**Issue by pvandervelde** [themotleyfool/Klondike#70]
I've installed a default version of Klondike and for some reason I cannot get the authentication to work correctly (or at least do what I would expect it to do).

Steps:
* I have a clean Win2012R2 machine with IIS installed with default settings
* Created a nuget folder in the wwwroot
* I downloaded the latest build from the master branch of appveyor (https://ci.appveyor.com/project/chriseldredge/klondike/build/74)
* Unzipped and copied all the klondike files to the wwwroot\nuget folder, made no changes to the web.config or the settings.xml files
* In IIS manager turned the nuget folder into an application (right-clicked the folder and selected 'turn into application'). Using a custom AppPool with the following settings:
  * .NET CLR version v4.0
  * Managed pipeline mode: Integrated
  * Running as a domain user so that it can get to the share folders
  * Maximum worker processes: 1
  * Disable overlapped recycle: True
* For the first test I used: authentication settings -> Anonymous Authentication: Enabled, everything else disabled
* For the second test I used: authentication settings -> Windows Authentication: Enabled, everything else disabled

Issues:
* There is no log-in link anywhere. If I hit a non-existing URL (e.g. localhost/nuget/api) then I can see the authentication credentials. In the case of anonymous authentication obviouslyl there are no credentials and when using windows authentication I can see my full user name (DOMAIN\UserName) if I use IE. If I use Firefox I get a log-in dialog which requests my credentials. So in either case it looks like the authentication details are passed on when requested.
* If I enable Windows Authentication and I add my user name to the web.config under both the AccountAdministrator and the PackageManager rolemappings, the links for admin / etc. etc. are missing. Even if I add both MyUserName and DOMAIN\MyUserName to the list.
* I see no logs begin produced anywhere. I've created the App_Data\Logs folders but still no logs.

As a minor issue I cannot see a footer that contains the klondike version (as there apparently should as indicated in #69)

I'm assuming I've not taken all the right steps to set up the website but unfortunately I don't know what I missed. I don't normally set up websites and the documentation is missing the 'for dummies' section.

**Comment by dankarmy** [comment]
hi,

It's not clear whether you want to force people to use a challenge response in their browser or enable anonymous access.

If you want to enable anonymous access you need to set the NTFS permissions on the nuget folder to the account which runs the app pool in IIS. Usually IIS_IUSR or iUSR.

Once you do this, you should be able to navigate to the URL (try using Nuget Package browser in Visual Studio or something).

Word of warning though, I haven't been able to get the front-end to work correctly on windows as you have to build it using node (which I've done), but just get a shit ton of js errors. The back-end works okay though.

**Comment by pvandervelde** [comment]
The ultimate goal is to enable Windows Authentication so that it works with our AD. I was just trying the anonymous authentication to see if I could make it show the links at all. 

The idea is that I don't want people to push packages by themselves, only the build server should be able to do that, so I was hoping that using the AD credentials (i.e. windows authentication) I would be able to stop people from being able to push packages and only allow the build server user to do so. 

I'll test the pushing of packages tomorrow when I'm back at work because so far I've only been trying to get the front end to work.

**Comment by pvandervelde** [comment]
Oh and obviously pulling packages should be possible either anonymously or with AD credentials (although I don't think nuget normally pushes those?). Not too fussed about the pulling of packages only pushing them up to the server should be done authenticated.

**Comment by dankarmy** [comment]
If you cannot get AD authentication to work, you could always try and API key route, see NuGet.Lucene.Web:localAdministratorApiKey in the web.config

You might be able to specify this on your build server.

**Comment by pvandervelde** [comment]
Ok I'll try going the API key route. It would be nice to have the front-end up and running but it's not essential at the moment. Is there a way I can create several API keys? e.g. one for the admin and one for the build server? Or are there no differences in the level of access between the different api keys?

**Comment by dankarmy** [comment]
I believe there is just one API key supported out of the box. If you dig through the code you might be able to find a way to implement more than one, but access is the same anyway.

 

If you ever manage to get the front end working give me a shout!

**Comment by pvandervelde** [comment]
I think I've stuffed it up somewhere because I can't push or list packages with the command line nuget tool. My app is at a sub-dir of the standard web site called nuget so I've tried:

* http://myserver/nuget
* http://myserver/nuget/api
* http://myserver/nuget/api/odata
* http://myserver/nuget/api/packages

And they all return a 404. I'm currently running it without an API key set and with anonymous authentication

Unfortunately the index.html page doesn't want to display the source URL bits either :( so I'm thinking it's gone horribly wrong.

**Comment by chriseldredge** [comment]
Which version of Klondike are you trying to deploy?

Generally the nuget client tools are not going to deal well with a child application because the client uses hard-coded paths. I can test out these scenarios and try to improve them, but for best results I strongly recommend that you deploy Klondike as a root application.

If you point your browser to `/api` you should see an api explorer that will show you what operations are possible, including creating, editing and deleting accounts and API keys.

**Comment by chriseldredge** [comment]
Sorry, I see now you are working with build 74. These builds are in beta and may contain bugs you are running into. First I'd try deploying as a root application to see if that helps.

**Comment by pvandervelde** [comment]
Ok sweet I'll try running as a root application first then.

**Comment by pvandervelde** [comment]
So first update: If you run as a root application then some of the issues with the page not showing correctly go away. So I guess the fix for the original bug reported is to make sure you run as a root application. It may be useful to add that to the readme / documentation somewhere so that silly people like me don't try to run as a child application.

**Comment by pvandervelde** [comment]
So pushing normal packages (i.e mypackage.nupkg) works but pushing symbol packages (mypackage.symbols.nupkg) fails with an error like this:

Pushing to http://myserver fails with:

    Failed to process request. 'Not Implemented'.
    The remote server returned an error: (501) Not Implemented..

And pushing to http://myserver/api fails with:

    Failed to process request. 'Method Not Allowed'.
    The remote server returned an error: (405) Method Not Allowed..

So I'm not quite sure where to push the symbol packages to and I haven't been able to find any documentation about this either. However I will keep looking to see if I can find something.

**Comment by chriseldredge** [comment]
From now on, symbol packages should be pushed to `/api/symbols`, but before you can successsfully push packages, you must have installed the Debugging Tools for Windows and you need to edit Settings.config to point Klondike to where the tools are installed. The HTTP 501 indicates that Klondike cannot find the debugging tools necessary to process the package.

**Comment by pvandervelde** [comment]
Sweet that worked! Awesome. Thanks for all the help!

**Comment by chriseldredge** [comment]
I added some notes warning about child applications. Thanks for the feedback.
