### ISSUE TITLE
Klondike prompts for credentials continuously

### ISSUE THREAD

**Issue by pkorsukov** [themotleyfool/Klondike#71]
I am trying to use Klondike release as a Nuget server using standard Nuget.exe to get a list of the packages. It always prompts for credentials and do not accept any credentials. I have researched using Fiddler and it seems like address `/api/OData` do not accept any credentials even if authorization rules allows everyone.
So, even from browser the URL `http://<my server>/<app folder>/api/OData` do not accept any credentials.
The Klondike home page and api are showing fine.

**Comment by chriseldredge** [comment]
By default, Klondike allows anonymous read access to the package feed. Are you able to view the Klondike web site in a browser without signing in? Have you enabled Anonymous Authentication on the IIS Manager?

**Comment by pkorsukov** [comment]
@chriseldredge I have found a cause. It looks like the `roleMappings` are not working. When I put any value to it, the `api/OData` rejects my credentials, even if the user in the right role.
```xml
  <roleMappings>
    <add key="PackageManager" value="Administrators" />
    <add key="AccountAdministrator" value="Administrators" />
  </roleMappings>
```

I am trying to configure the Nuget to be available for authorized users only. It was managed by IIS authorization rules. Additionally I try to allow package and user management only for certain AD role. And than I receive the problem. Here is the result of my tests:

Anonymous + Windows Auth
Can see the page - `/`
Can see the page - `/api/`
Can see the page - `/api/OData`


Windows Auth Only
Can see the page - `/`
Can see the page - `/api/`
Can see the page - `/api/OData`

Windows Auth + Role mapping:
Can see the page - `/`
Can see the page - `/api/`
Always prompts for the credentials and do not accept it - `/api/OData`

The anonymous auth for me is not acceptable option. It would be great to have some support for the windows auth and role mapping. Here is the related auth config:
```xml
<system.webServer>
    ........
    <security>
            <authentication>
                <anonymousAuthentication enabled="false" />
            </authentication>
            <authorization>
                <remove users="*" roles="" verbs="" />
                <add accessType="Allow" roles="Administrators" />
                <add accessType="Allow" users="domain\user" />	
            </authorization>
    </security>
  </system.webServer>
```

**Comment by chriseldredge** [comment]
Are you using build 79 from AppVeyor? I found a problem last week with Klondike's authentication middleware that prevented it from working properly when anonymous authentication is disabled. If you are using build 79, there could be additional problems.

https://ci.appveyor.com/project/chriseldredge/klondike/build/79/artifacts

**Comment by chriseldredge** [comment]
Found another problem with the role mapping middleware. I believe this issue is resolved in build 82.

**Comment by chriseldredge** [comment]
I believe this is fixed. Please open a new issue if you see authentication problems on recent builds.
