### ISSUE TITLE
Question:  Configuring package path for UNC path to remote share on NAS device

### ISSUE THREAD

**Issue by djl2** [themotleyfool/Klondike#72]
We've been storing our packages on our Klondike server's local physical D: drive. We currently have over 55K package files stored (455GB).  We plan to move our packages to a remote NAS share and configure the web.config for NuGet.Lucene.Web:PackagesPath =  \\Hostname\share.

The web.config comments state that it's possible to point to a virtual share in the PackagePath, but I would like to know if we can expect any issues with this configuration.

Do you have any experience with such a configuration?  Could there be possible issues with the indexer running over the network with such a large number of files?

Your thoughts would be appreciated.  Thanks in advance

**Comment by chriseldredge** [comment]
I don't personally have experience with using a UNC share to keep packages, but I don't foresee any problems other than a performance hit from the extra network hop.

You may have problems using the file system watcher, but if you're pushing packages exclusively over http, you don't need that feature enabled.

You also may need to set ACLs to allow access from your app pool identity to be able to access the share and files within.

**Comment by djl2** [comment]
Thanks for the feedback.  It seems to work, though we still need to do more performance testing.
