### ISSUE TITLE
Packages that target .NET 4.0 Client should appear on projects targeting .NET 4.0 Standard

### ISSUE THREAD

**Issue by smadam813** [themotleyfool/Klondike#73]
We have two packages in our repository that are unable to be searched for using the VS Package Manager after upgrading to Build 82.  Their names are "Company.Libraries.Crypto" and "Company.Libraries.Crypto.Api".  I have not been able to identify any other naming schemes that create this issue so I am wondering if Crypto is a reserved word.  The package search within Klondike's web interface works 100% even with the packages listed above.

**Comment by chriseldredge** [comment]
This certainly sounds odd. The web interface and OData api that VS Package Manager uses ultimately go through the same code path so I'm not sure off the top of my head why one would behave differently than another.

Is it possible that the VS Package Manager is sending a target framework version that Klondike thinks is not compatible with the package?

For testing purposes, could you provide a (scrubbed) example nuspec and list of files/folders contained in the package?

**Comment by smadam813** [comment]
Unfortunately I cannot provide any files/folders as is.  I will work on crafting a package with a similar structure though in the meantime.

The pre 2.0 Klondike works 100% with this package, so if the logic for capturing target framework has not changed, I do no think that is it.

**Comment by chriseldredge** [comment]
At the time v1.6.2 was released, the target framework parameter was sent from the client but NuGet Gallery and other servers simply ignored it, presumably out of difficulty of correct implementation. In the months since then, www.nuget.org does now filter on target framework, and logic was added to Klondike 2.0 to do something similar. That code has not been widely tested and may produce unexpected or wrong results.

**Comment by smadam813** [comment]
I think you are spot on.  This particular project had .NET 4.0 Client Profile as its target framework instead of Standard .NET 4.0.  I am going to switch it and see if it shows up within the search.

**Comment by smadam813** [comment]
My only issue right now with this package is .NET 4.0 Client Profile is a supported framework by standard .NET 4.0 solutions.  This package shouldn't need to be the Standard .NET 4.0 framework in order to show up in the VS search.  I still think this is an issue with the logic in the latest Klondike version.

**Comment by chriseldredge** [comment]
Sounds like it. So the package targets .NET 4.0 Client Profile and it isn't showing up for a project that targets .NET 4.0 (Standard).

I'll make a test case for this and verify.

Incidentally, the logic for which framework versions are compatible with other framework versions is not something built into NuGet.Core.dll, or anywhere else I've found that Klondike could reuse. I've had to reimplement this logic to the best of my ability. The logic is brittle and prone to need touching up every time a new framework is introduced.

**Comment by chriseldredge** [comment]
This turned out to be a case-sensitivity bug. The short name is `net40-Client` and Klondike was converting it to lowercase in one place and not in another.

Fixed by https://github.com/themotleyfool/NuGet.Lucene/commit/c0d44b8ad9173142a67d70368194c2af8bd0c53a

**Comment by chriseldredge** [comment]
This should work correctly in Klondike build 84.

https://ci.appveyor.com/project/chriseldredge/klondike/build/84/artifacts
