### ISSUE TITLE
API/Users doesn't return user key and roles but API/Session does

### ISSUE THREAD

**Issue by pvandervelde** [themotleyfool/Klondike#74]
If I access `api/users` then I get this:

    [
      {
        "username": "AUCKLAND/Patrick.VanDerVelde",
        "key": null,
        "roles": null
      },
      {
        "username": "LocalAdministrator",
        "key": null,
        "roles": null
      }
    ]

But when I access `api/session` I get this
 
    {
      "username": "AUCKLAND/Patrick.VanDerVelde",
      "key": "7bf5c567-a51f-409b-9bc5-a8158f4e6966",
      "roles": [
        "AccountAdministrator",
        "PackageManager"
      ]
    }

I would expect `api/users` to return the same information? Or is that not the case for security reasons. In that case does that still apply when the session user is actually the account administrator because the klondike website happily shows me all the information, just the REST api doesn't.

**Comment by chriseldredge** [comment]
You answered your own question. The code in question can be found at https://github.com/themotleyfool/NuGet.Lucene/blob/master/source/NuGet.Lucene.Web/Controllers/UsersController.cs#L214 and removes the api key and roles when the request user is not authenticated or is not in the `AccountAdministrator` role.

If the request is authenticated, this information is *not* removed for a username matching the authenticated username.

The design is (a) anonymous users can see a list of users, or (b) authenticated non-admin users can see their own key and permissions, or (c) authenticated admin users can see all info for all users.

**Comment by pvandervelde** [comment]
That makes total sense. The only thing I don't understand in that case is that `api/session` only returns a value if the session is authenticated. So from that I conclude that if I get data back that means that the session is authenticated (somehow). And given that `api/session` returned my user name and key I'm assuming I'm authenticated as me. I'm also in the AccountAdministrator role as per the information returned from `api/session` so that means I should fall in option c) in your answer, i.e. I'm an authenticated user who is an AccountAdministrator, hence I should be able to see all the information for all users when I call `api/users`. 

So with that the question is how I can see whether the call to `api/users` is running in an authenticated session as well?

**Comment by chriseldredge** [comment]
This sounds like a pitfall of mixed authentication modes. `api/session` will require authentication, and if you have Windows Authentication enabled this will happen transparently with NTLM. `api/users`, by default, does not require authentication, but supports authenticated requests. As a result, the NTLM handshake never occurs, so even though you may have previously authenticated on a different request, this request is treated as anonymous.

You can force authentication to happen by sending the `X-NuGet-ApiKey` header on the request to `api/users` (as the Klondike web app does) or by disabling anonymous authentication in IIS, which would force NTLM to authenticate the request.

Perhaps a response header or other metadata could be included in the response from `api/users` that indicates what mode of authentication the server is operating under to make it more clear.

**Comment by pvandervelde** [comment]
Ah right. I do indeed have Windows authentication enabled so `api/session` will get my user credentials automatically. However all other forms of authentication are disabled so in theory `api/users` should authenticate but I can see how it might not(?). For my current use case I don't really care about this because I can just get the API token for the current user from the `api/session` call.

Having the authentication mode included in the response header would at least allow users to determine what their authentication state is so that might well be worthwhile having. In any case thanks for clearing up the confusion again :)
