### ISSUE TITLE
The relative virtual path 'index.html' is not allowed here.

### ISSUE THREAD

**Issue by drphrozen** [themotleyfool/Klondike#75]
In build 99 i got the following:

The relative virtual path 'index.html' is not allowed here.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.ArgumentException: The relative virtual path 'index.html' is not allowed here.

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:

[ArgumentException: The relative virtual path 'index.html' is not allowed here.]
   System.Web.Hosting.HostingEnvironment.MapPathActual(VirtualPath virtualPath, Boolean permitNull) +12489322
   System.Web.Hosting.HostingEnvironment.MapPath(VirtualPath virtualPath) +149
   Klondike.WebHostVirtualPathUtility.MapPath(String virtualPath) in c:\git\Klondike\src\Klondike.WebHost\IVirtualPathUtility.cs:32
   Klondike.Startup.Start(IAppBuilder app, IContainer container) in c:\git\Klondike\src\Klondike.WebHost\Startup.cs:50
   NuGet.Lucene.Web.Startup.Configuration(IAppBuilder app) in c:\projects\nuget-lucene\source\NuGet.Lucene.Web\Startup.cs:44

**Comment by drphrozen** [comment]
I solved my issue by prefixing ~/ to index.html in Startup.cs under WebHost

**Comment by drphrozen** [comment]
Using IIS 7.5, i don't know if this will interfere with the fix in db2e03066085bebbc662061ef7be88b5446835b5

**Comment by chriseldredge** [comment]
Using `~/index.html` seems to work right in both IIS and self-host. Added in 07d2be0d83e2948546da25644aa470e122e6cae3.
