### ISSUE TITLE
Use AD authentication for package read but disallow package pushing

### ISSUE THREAD

**Issue by pvandervelde** [themotleyfool/Klondike#78]
I've got a klondike version (Klondike 2.0.0-beta.fe6acc3d) running on a test server. I've set up IIS (8 on win2012R2) to use windows authentication with our AD which seems to work fine. 

The last thing I want to do is to allow everybody on the AD to list and pull packages from the repository but only allow a select few users to push packages to the repository (i.e. only the build server and the admin). I'm not entirely sure how I would go about achieving this though because every user has on their own page an API key which means they could push packages up. Is there a way to stop people from pushing packages?

**Comment by chriseldredge** [comment]
Everyone gets an API key whether they are authorized to do something with it or not. You can manually assign permissions (roles) to accounts by browsing to Klondike's front-end in your browser, logging in (or as LocalAdministrator), navigating to Admin, then Account Management.

If you want users in a pre-defined Active Directory group to automatically inherit roles, the best way to do this is by editing [Web.config](https://github.com/themotleyfool/Klondike/blob/master/src/Klondike.WebHost/Web.config). See the `roleMappings` section and preceding comment.

The `PackageManager` role is the one that allows authenticated users to push and delete packages.

**Comment by pvandervelde** [comment]
Ok that's the information I was missing, what permissions the `PackageManager` role actually provides. Are there any other roles other than `PackageManager` and `AccountAdministrator` that can be set in the `web.config`. Also is there an overview somewhere of what permissions the different roles grant?

**Comment by chriseldredge** [comment]
Those are the only 2 roles.

Besides the comment in Web.config, there is the README.md that has some information about authentication and authorization. Perhaps it could made more clear in the README what the roles allow. a PR would be welcome :)

**Comment by pvandervelde** [comment]
Done. PR is #80

**Comment by chriseldredge** [comment]
Merged. Thanks!
