### ISSUE TITLE
POST api for synchronize package

### ISSUE THREAD

**Issue by xtheary** [themotleyfool/Klondike#79]
Hi,
I am trying to use the POST api to synchronize the package because we have notice the nuget feeds does not always get updated automatically even if the FileSystemWatcher is on . When I push the button SUBMIT on the Api page under the Synchronize section, it always prompt an authentication required window and any account that I tried has failed me so far. What account/password am I supposed to use there?
I am using Klondike-Release-2.0.0.0beta1
Thanks

**Comment by chriseldredge** [comment]
An authenticated user needs to have the PackageManager role granted. You can grant this role in a couple ways: edit Web.config and map it to an Active Directory group in `<roleMappings>`, or browse Klondike and navigate to Admin, then Manage Accounts, then the account in question, and grant roles there.
