### ISSUE TITLE
Authentication failed for users other than local administrator.

### ISSUE THREAD

**Issue by polarbit** [themotleyfool/Klondike#81]
Firstly, Thank you for your work, this is the only project currenly we use as a nuget server in private. 

My problem is, when I try to sign-in from a not-local machine to klondike I get an error that says authentication failed. Is there something that I need to enable sign in ?

I correctly created account admin and package admin accounts. I can manage packages; but can not manage account.

**Comment by chriseldredge** [comment]
If you want to authenticate in the browser, that authentication is handled externally, e.g. by Active Directory or another authentication provider configured in Web.config. When managing accounts in the browser, you are creating accounts, assigning API Keys and assigning roles to accounts.

Currently the browser application does not support authentication by Api Key, but you would be able to use these keys in an HTTP client (such as curl) by sending it in the `X-NuGet-ApiKey` request header.

Perhaps the browser app should support authenticating by Api Key.

**Comment by polarbit** [comment]
I understand, thank you for your answer.
