### ISSUE TITLE
Klondike doesn't detect symbols for native packages generated by CoApp tools.

### ISSUE THREAD

**Issue by silicondwarf** [themotleyfool/Klondike#84]
Related to: Klondike-Release-2.0.0-beta1

Hi Chris,
According to our discussion on your blog:

http://chris.eldredge.io/blog/2015/01/05/nuget-symbols-and-aspnet-vnext/#comment-2035618712

I tried to push the symbol packages directly to the URL: /api/symbols

`Pushing cryptopp.symbols 5.6.2.0 to 'http://localhost:8080/api/symbols'...`

The server responded with:

`Failed to process request. 'Bad Request'.`
`The remote server returned an error: (400) Bad Request..`

I also modified CoApp configuration, that PDBs were stored in the lib folder of the package.
But the issue that symbol packages aren't detected still exists.

As you suggested, here is a sample package generated by CoApp:

[ Edit: Link to sample package has been removed]

Kind regards
Andi Weber

**Comment by chriseldredge** [comment]
I can change Klondike to look for pdb files anywhere in packages.

However, when I run `srctool -r` on any of the pdb files in your sample package, it outputs:

    No source information in pdb for ./build/native/bin/Win32/Debug/v110/CryptoPPLibD.pdb.

I'm not familiar with symbols for native assemblies, but Klondike will not be able to server source code unless this command or another one is able to see source code references inside the pdbs.

**Comment by silicondwarf** [comment]
I will investigate whats wrong with the source information. Maybe it is a wrong setting in the original CryptoPP VS-project where the samples where generated from.
But am I right that there is also a problem finding the PDB's in the package?
Would it be possible to copy the PDB's and source files manually to Klondike's symbol directories as a workaround until the detection is fixed (if you consider to fix it).

**Comment by silicondwarf** [comment]
I investigated the reason for the missing source information in the PDB files.
The provided example package only contain static libraries. As a static lib isn't a executable like an EXE or DLL, they aren't loaded by the debugger. A executable linking against a static lib will include the source information from the lib into its PDB file if the PDB of the lib is available at link time. If I think about it, this is absolutly logical and makes sense. Therefore a symbole package makes no sense for the provided example. I should put the PDB's beside the LIB files in the default package to make them available at link time to the consuming project.

I will provide new example packages for testing tomorrow, that contain DLLs and PDBs with valid source information.

**Comment by silicondwarf** [comment]
I prepared new sample packages!

See: https://share.cryptas.com/pydio/data/public/63ad9ac63aaa64b075632f1d.php

This package is providing DLLs instead of static libraries. These packages (default, redist, symbols) were generated by CoApp without any additional tweaks. So they should be suitable for testing Klondike's compatibility with native NuGet packages.

**Comment by chriseldredge** [comment]
I've just pushed up https://github.com/themotleyfool/NuGet.Lucene/commit/7ce77e757dec548eaad3d3c6e1f15369888cff85 to NuGet.Lucene and will update Klondike to use the new build.

This commit relaxes the searching for `*.pdb` to find the files anywhere in the nupkg, not just in `/lib/`.

I successfully pushed your sample package with this change, but I'm not really able to tell if it works end-to-end with Visual Studio debugger or windbg.

**Comment by silicondwarf** [comment]
Thank you for fixing! I'm looking forward to an updated version of Klondike.

I have to remove the sample packages from the linked share, because my personal space is very limited there. Feel free to keep the already downloaded packages for regression testing, etc.

**Comment by chriseldredge** [comment]
Please try latest build from https://ci.appveyor.com/project/chriseldredge/klondike/build/96/artifacts.

**Comment by silicondwarf** [comment]
I tried the linked build and ran `Klondike.SelfHost.exe` for testing. This build __doesn't work__ as expected. I'm able to upload packages to Klondike but the symbol package isn't recognized correctly. Please, see the attached screenshots.

![klondike_1](https://cloud.githubusercontent.com/assets/3699078/8005154/0e99271c-0b87-11e5-82a8-e5bd70a0587e.png)
![klondike_2](https://cloud.githubusercontent.com/assets/3699078/8005158/15d4afb0-0b87-11e5-8c27-ef36e619acd6.png)

There was no 'Symbols' folder created under 'App_Data'. Maybe there is something wrong with my configuration or access rights.

* `Klondike.Selfhost.exe` was started as Administrator from command line in interactive mode
* There were no errors reported.
* debuggingToolsPath is set to `C:\Program Files (x86)\Windows Kits\8.1\Debuggers\x64`
* All other config settings are untouched (default values)

Have you already performed a successful test with the provided build?

**Comment by chriseldredge** [comment]
Oops, looks like I managed to update NuGet.Lucene.Web in this build without updating NuGet.Lucene.

**Comment by chriseldredge** [comment]
Build 97 should actually work :) I even tested it this time.

https://ci.appveyor.com/project/chriseldredge/klondike/build/97/artifacts

**Comment by silicondwarf** [comment]
Build 97 is working! The symbol package has been detected successfully. But i noticed, that in the WebUI view of the main package, the warning message "Symbols and source code are not available for this package." is still be displayed. The message doesn't bother me, but maybe you'll find some time having a look to this.

**Comment by chriseldredge** [comment]
That's odd. On my test instance I get the green debug icon and message "Symbols and source code are available for this package." I'm not sure why your system is behaving differently, but the code is checking if a symbol package is present in the configured symbol directory. See [SymbolSource.cs#L28](https://github.com/themotleyfool/NuGet.Lucene/blob/7ce77e757dec548eaad3d3c6e1f15369888cff85/source/NuGet.Lucene.Web/Symbols/SymbolSource.cs#L28).

**Comment by silicondwarf** [comment]
That's weird! I have some questing regarding your environment.
- Is your test instance also running Build 97?
- Have you tested with the Cryptopp sample packages provided by me?
- Do you use the self hosted or IIS version for testing?

**Comment by chriseldredge** [comment]
@silicondwarf I'm getting pretty close to releasing 2.0 and want to confirm this is fixed. If you have some time, can you upgrade to this build: https://ci.appveyor.com/project/chriseldredge/klondike/build/115/artifacts and let me know if it's working as expected?

**Comment by silicondwarf** [comment]
Hi Chris,
I tested with your build #115 as Self-hosted version. There is no diffrence between the actual build and build #97. As I already wrote in my comment on 8. Jun. The symbol package is imported sucessfully into the repo. But there is still the bug on the GUI. "Symbols and source code are not available for this package." But I don't really care about the GUI bug. So feel free to close this issue.

**Comment by silicondwarf** [comment]
Sorry I closed this issue by mistake. Maybe you would like to keep it open because the GUI bug is still there. But as I wrote in the comment above: Feel free to close it again if you can't reproduce it.

**Comment by chriseldredge** [comment]
I would like to investigate the UI bug but I don't have the sample packages you provided previously. If you have the time and inclination to provide me with new samples I'll take another look. Otherwise I'll probably just move on.

**Comment by silicondwarf** [comment]
Samples are available [here...]
(https://drive.google.com/folderview?id=0B3Z9bKw6Qyltfi11Zy1WT3lGdk1yaFBMb0dvUXgtNUtJc1VWYzMzcFl4REgwUXI1VFVjdnM&usp=sharing)

**Comment by chriseldredge** [comment]
Got them, thanks.

**Comment by chriseldredge** [comment]
Finally got around to testing this against commit 439bd85b ([build 119](https://ci.appveyor.com/project/chriseldredge/klondike/build/119/artifacts)).

```
nuget push cryptopp.5.6.2.0.nupkg -source http://localhost:9001/api/packages
Pushing cryptopp.symbols 5.6.2.0 to 'http://localhost:9001/api/packages'...
Your package was pushed.
```

Next I went to `/packages/cryptopp.symbols/5.6.2.0` in the browser and see the message "Symbols and source code are *not* available for this package."

Then I pushed the symbols:

```
nuget push cryptopp.symbols.5.6.2.0.symbols.nupkg -source http://localhost:9001/api/packages
Pushing cryptopp.symbols 5.6.2.0 to 'http://localhost:9001/api/packages'...
Your package was pushed.
```

When I refreshed the package info page in my Browser, the message now says "Symbols and source code are available for this package."

I can't reproduce the problem. Since it's a minor issue for you, I'm gonna give up here.
