### ISSUE TITLE
Unable to push packages cleanly

### ISSUE THREAD

**Issue by mortenn** [themotleyfool/Klondike#85]
Hello!

I have a project where the post-build event command line publishes new nupkg files.
But, after attempting to move over to a nuget server, this is failing when I try pushing to klondike.

1>  Attempting to build symbols package for 'xxx.csproj'.
1>  Packing files from 'C:\...\bin\Release'.
1>  Found packages.config. Using packages listed as dependencies
1>  Successfully created package 'C:\...\bin\Release\xxx.1.46.5630.30092.symbols.nupkg'.
1>  Pushing xxx 1.46.5630.30092 to 'https://nuget.xxx.no/api/'...
1>  Your package was pushed.
1>  Pushing xxx 1.46.5630.30092 to 'https://nuget.xxx.no/api/'...
1>  Failed to process request. 'Internal Server Error'. 

The event log on the server reveals the problem is:
The process cannot access the file 'C:\...\App_Data\Lucene\write.lock' because it is being used by another process.

I was also having trouble setting klondike up on a webfarm behind MS' ARR for similar reasons, but the server is now running on an old box without load balancing/redundancy.

**Comment by chriseldredge** [comment]
As the README states, Klondike is not designed to run in a Web Farm or any other clustered configuration. See https://github.com/themotleyfool/Klondike#app-pool-advanced-configuration.

I know this is a design flaw that limits Klondike when a server is unreachable or unhealthy but haven't had time to work on a clustered configuration, which would take a substantial amount of effort to do right.

**Comment by mortenn** [comment]
This issue is not about the clustered configuration. I am unable to push multiple nupkgs in short succession to a single host

**Comment by lukeskinner** [comment]
Have you checked the following 2 settings on the app pool? (from the [README](https://github.com/themotleyfool/Klondike#app-pool-advanced-configuration))
- Make sure Maximum Worker Processes is set to 1
- Make sure Disable Overlapped Recycle is set to true

The error ```The process cannot access the file 'C:...\App_Data\Lucene\write.lock' because it is being used by another process.``` will only appear when multiple instances of Klondike are running or the app pool is configured incorrectly. If those settings are correct you could try stopping the website/app pool, deleting the write.lock file and starting the website again (it will re-create the write.lock file). 

On a quick test I was able to push 6 packages in a row (3 packages + 3 symbol packages) without any errors.

**Comment by mortenn** [comment]
Yes, I did make those settings on the app pool.. maximum worker was already set to 1, but I changed the other one to true when I installed klondike..
