### ISSUE TITLE
Can I run two instances pointing at the same packages folder

### ISSUE THREAD

**Issue by calvinv** [themotleyfool/Klondike#88]
Hey,

I basically want to setup a beta site on the same server that points to the same packages folder as my main site so upgrading can be a simple binding switch. The beta site won't have anything pushed to it and will have a different index path. 

Do you know of any reason this would bring down the main site?

Thanks,
Calvin

**Comment by chriseldredge** [comment]
Having two instances share a package directory should work fine as long as each has it's own Lucene index directory. If you want packages pushed by one instance to show up in the other, you would need to enable the file system watcher in one or both of the instances.

Some metadata will not match perfectly between the two instances, but nothing essential would be out of sync.

**Comment by calvinv** [comment]
Thanks, this is great
