### ISSUE TITLE
Package dependencies are not mirrored

### ISSUE THREAD

**Issue by Useurmind** [themotleyfool/Klondike#89]
I tested Klondike for evaluation pruposes. We want to mirror the packages used in our company to be save in case something happens with the original nuget repository.

The problem is the following. It seems to me klondike does not mirror the dependencies of a package I installed via the Klondike server.

I used the following command line to install the package
nuget.exe install packageIdWithDependencies -source http://localhost -nocache

1. I installed the package with Internet connection, everything worked fine and the package was shown as being mirrored by Klondike. Strangely the dependencies were not shown as being mirrored.
2. I removed the Internet connection and the installed packages and did the same again. Worked fine.
3. I restarted the PC, removed the installed packages and did the same. Again, without Internet connection. Now it tells me that a dependency of the package I installed could not be resolved.

Could it be that Klondike holds the dependencies only in a cache that is deleted on restart?
If so it would be effectively nonsense to apply this server as a backup for safety reasons.

Can you help me with this? I really would like to give Klondike a chance in our company.

**Comment by chriseldredge** [comment]
Klondike makes no attempt to determine dependencies when mirroring a package. The NuGet client handles this. If the client determines that a given target framework configuration for a package has dependencies, the client will request to download those dependencies from Klondike in the same way it would request the primary package.

Is it possible that the NuGet client cache is leading to confusing results? NuGet keeps a local file cache in `~/App_Data/Local/NuGet/Cache`. The last time I checked there was no way to disable this local cache. You can try removing the directory completely before testing how Klondike mirrors packages with dependencies.

**Comment by Useurmind** [comment]
That does the trick. 

Seems the -nocache option didn't have the effect I supposed it would have... 

Thank you! :)

**Comment by chriseldredge** [comment]
It feels like NuGet has 8 layers of cache, and `-NoCache` only disables one of them :)
