### ISSUE TITLE
Deleting packages does not remove it from the package page even after reindexing

### ISSUE THREAD

**Issue by pvandervelde** [themotleyfool/Klondike#91]
When I delete a package via the http API by making a DELETE http call to http://myserver/api/packages/mypackage/myversion, e.g. in powershell by doing:

    Invoke-WebResponse -Uri http://myserver/api/packages/mypackage/myversion -Method Delete

 then I get the following response

    StatusCode        : 200
    StatusDescription : OK
    Content           : {}
    RawContent        : HTTP/1.1 200 OK
                        Persistent-Auth: true
                        Content-Length: 0
                        Date: Thu, 18 Jun 2015 00:12:56 GMT
                        Server: Microsoft-IIS/8.5
                        WWW-Authenticate: Negotiate oYG2MIGzoAMKAQChCwYJKoZIgvcSAQICooGeBIGbYIGYBgkqh...
    Headers           : {[Persistent-Auth, true], [Content-Length, 0], [Date, Thu, 18 Jun 2015 00:12:56 GMT], [Server, Microsoft-IIS/8.5]...}
    RawContentLength  : 0

Looking in the storage directory the package is indeed gone. When I try to grab the package with nuget it fails with a message saying that the package does not exist.

But it's not gone from the web page. Even if I click the 'Synchronize Packages' and 'Rebuild Index' buttons on the admin page.

**Comment by navidmatin** [comment]
I believe there is an issue with the Frontend that shows the packages. I moved around 200Mb of packages to the package folder and synced it but the packages part of the website doesn't show any packages (however it says there are 273 packages). I realized I can still search through the packages through API.

**Comment by chriseldredge** [comment]
The front-end app caches some information and does not always expire caches properly when packages are pushed, deleted or synced with the file system. A full refresh should clear the cache. There is probably something I can do to invalidate cache whenever a status message is send to the browser via SignalR.

**Comment by pvandervelde** [comment]
Does the cache get deleted / cleared when you restart the web site / apppool? I anticipate deleting packages will be extremely rare so it's not a big issue but it is confusing if the front-end still shows the packages when they should be gone. Recycling the apppool would be an acceptable work around.

**Comment by chriseldredge** [comment]
The cache only exists in the browser when you are using the Ember front-end. Doing a full refresh of the page is all that is needed to clear this cache.

**Comment by pvandervelde** [comment]
Ok that makes sense. Will do that in the future.
