### ISSUE TITLE
Add access log with status code and message

### ISSUE THREAD

**Issue by pvandervelde** [themotleyfool/Klondike#93]
If you have 'showExceptionDetails' turned off in the Klondike configuration it is possible that exceptions (like having no sources in a symbol package) are only reported in generic error codes. This makes it hard to debug these situations. Adding some information to the Klondike log (or the IIS log) would make it easier to figure out where things went wrong.

**Comment by chriseldredge** [comment]
This particular error is a `400 Bad Request` and originates from [SymbolsController](https://github.com/themotleyfool/NuGet.Lucene/blob/master/source/NuGet.Lucene.Web/Controllers/SymbolsController.cs#L69).

I agree it is unfortunate that the NuGet.exe client does not pass the underlying error message through so the user can see what went wrong.

**Comment by chriseldredge** [comment]
If you are using IIS, you can use the built-in [httpLogging](http://www.iis.net/configreference/system.webserver/httplogging) component for logging failed requests. I'm not sure if it would log the status message or only the status code.

**Comment by pvandervelde** [comment]
Yeah I found where the error comes by going over the source. I've fixed the specific package that was giving me the error based on that error message. I'll turn on the httpLogging and we'll see what output I'm getting from that.
