### ISSUE TITLE
Klondike does not send a response to the client when an exception goes uncaught

### ISSUE THREAD

**Issue by benjamincburns** [themotleyfool/Klondike#94]
During testing for #86, I noticed that the outcome for the client for such uncaught exceptions is a response timeout.

Ideally uncaught exceptions would trigger an error to be registered in the client with information in the response which gives the user of the client something meaningful to report to the administrator of the Klondike server (even if this error is simply just the `Message` property of the uncaught exception).

**Comment by chriseldredge** [comment]
This is when you push a package that Klondike fails to index? #86 seems to be related to synchronizing packages with the file system so I want to make sure I understand.

**Comment by chriseldredge** [comment]
I'm not sure how to reproduce this problem. Can you provide additional information on what you did that resulting in a timeout?

**Comment by chriseldredge** [comment]
I can't reproduce this problem without more information. Feel free to reopen if you can provide instructions on how to do that.
