### ISSUE TITLE
Breaking error: cannot access file "write.lock" even when configured for single-thread

### ISSUE THREAD

**Issue by tysonstewart** [themotleyfool/Klondike#96]
Same as #48. The first time it happened, I changed the configuration according to the documentation so that `Maximum Worker Processes` was set to 1 and `Disable Overlapped Recycle` is set to True.
![image](https://cloud.githubusercontent.com/assets/1292640/8780308/c6645f60-2ecd-11e5-9b12-b4412b1e41e3.png)

We still received this error. Stopping and starting the application pool did get the server working again, but this is kind of annoying as it breaks all builds in the mean time. 

We are running Version 1.6.2 (f76e0ed). 

I captured a screenshot of the exception, but didn't think to actually copy the content. I apologize for that, but here's what I do have:

![screen shot 2015-07-20 at 10 43 36 am](https://cloud.githubusercontent.com/assets/1292640/8780379/2b569dc0-2ece-11e5-911d-ebff2a60fc11.png)

== Update ==

Happened again today. Here's the stack trace:
```
[IOException: The process cannot access the file 'Z:\Lucene\write.lock' because it is being used by another process.]
   System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) +14460923
   System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) +1430
   System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy) +205
   System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access) +84
   Lucene.Net.Store.NativeFSLock.Obtain() in d:\Lucene.Net\FullRepo\trunk\src\core\Store\NativeFSLockFactory.cs:240

[LockObtainFailedException: Lock obtain timed out: NativeFSLock@Z:\Lucene\write.lock: System.IO.IOException: The process cannot access the file 'Z:\Lucene\write.lock' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Lucene.Net.Store.NativeFSLock.Obtain() in d:\Lucene.Net\FullRepo\trunk\src\core\Store\NativeFSLockFactory.cs:line 240]
   Lucene.Net.Store.Lock.Obtain(Int64 lockWaitTimeout) in d:\Lucene.Net\FullRepo\trunk\src\core\Store\Lock.cs:83
   Lucene.Net.Index.IndexWriter.Init(Directory d, Analyzer a, Boolean create, IndexDeletionPolicy deletionPolicy, Int32 maxFieldLength, IndexingChain indexingChain, IndexCommit commit) in d:\Lucene.Net\FullRepo\trunk\src\core\Index\IndexWriter.cs:1228
   Lucene.Net.Index.IndexWriter..ctor(Directory d, Analyzer a, Boolean create, IndexDeletionPolicy deletionPolicy, MaxFieldLength mfl) in d:\Lucene.Net\FullRepo\trunk\src\core\Index\IndexWriter.cs:1110
   Lucene.Net.Linq.LuceneDataProvider.GetIndexWriter(Analyzer analyzer) +109
   Lucene.Net.Linq.LuceneDataProvider.get_IndexWriter() +197
   Lucene.Net.Linq.LuceneDataProvider..ctor(Directory directory, Analyzer externalAnalyzer, Version version, IIndexWriter externalWriter, Object transactionLock) +263
   NuGet.Lucene.LuceneRepositoryConfigurator.InitializeLucene() +271
   NuGet.Lucene.LuceneRepositoryConfigurator.Initialize() +231
   NuGet.Lucene.Web.NuGetWebApiModule.Load() +214
   Ninject.KernelBase.Load(IEnumerable`1 m) in c:\Projects\Ninject\ninject\src\Ninject\KernelBase.cs:219
   Klondike.App_Start.NinjectWebCommon.CreateKernel() in c:\Projects\NuGet\Klondike\app\App_Start\NinjectWebCommon.cs:47
   Ninject.Web.Common.Bootstrapper.Initialize(Func`1 createKernelCallback) in c:\Projects\Ninject\Ninject.Web.Common\src\Ninject.Web.Common\Bootstrapper.cs:50
   Klondike.App_Start.NinjectWebCommon.Start() in c:\Projects\NuGet\Klondike\app\App_Start\NinjectWebCommon.cs:29

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +229
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +211
   System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) +35
   WebActivator.BaseActivationMethodAttribute.InvokeMethod() +341
   WebActivator.ActivationManager.RunActivationMethods() +787
   WebActivator.ActivationManager.RunPreStartMethods() +38
   WebActivator.ActivationManager.Run() +56

[InvalidOperationException: The pre-application start initialization method Run on type WebActivator.ActivationManager threw an exception with the following error message: Exception has been thrown by the target of an invocation..]
   System.Web.Compilation.BuildManager.InvokePreStartInitMethodsCore(ICollection`1 methods, Func`1 setHostingEnvironmentCultures) +12619651
   System.Web.Compilation.BuildManager.InvokePreStartInitMethods(ICollection`1 methods) +12619372
   System.Web.Compilation.BuildManager.CallPreStartInitMethods(String preStartInitListPath, Boolean&amp; isRefAssemblyLoaded) +280
   System.Web.Compilation.BuildManager.ExecutePreAppStart() +172
   System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel, Exception appDomainCreationException) +1151

[HttpException (0x80004005): The pre-application start initialization method Run on type WebActivator.ActivationManager threw an exception with the following error message: Exception has been thrown by the target of an invocation..]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +12618692
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +159
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +12458309
```

**Comment by chriseldredge** [comment]
Is there anything in the log prior to this indicating why the previous process was shut down? Do you have additional instances of w3wp.exe running or only the one?

**Comment by tysonstewart** [comment]
Thank you for responding @chriseldredge! I want to help as much as I can. Whenever I check, there is only one w3wp.exe process running. I don't see anything helpful in the logs, but you would be more knowledgeable than I am. I've copied the Klondike log files for [yesterday (2015-07-20)](https://gist.github.com/tysonstewart/8a0830e71d918d580e75) and [today (2015-07-21)](https://gist.github.com/tysonstewart/5007e7eeac97cd97fe77) to gists so you can see them. 

For 07-20, the Windows Application Event Log indicates the Klondike web application started throwing errors at 14:45:38.

For 07-21, the Event Log indicates Klondike started throwing errors at 16:45:25. 

All times are UTC.

The system logs aren't very helpful, I'm afraid. The only entries for Klondike are errors with the same exception as I pasted above. None talk about the application crashing or restarting.

The server is running Windows Server 2012 R2 on AWS.

**Comment by chriseldredge** [comment]
I see many errors in the attached logs but no instance of LockObtainFailedException. I wonder if some of the errors that are occurring are causing Klondike to crash without removing the lock file. I see you have process orphaning and overlapped recycle disabled, so this is my best guess.

```
System.InvalidOperationException: 'EntityFramework.Commands' already has a dependency defined for 'EntityFramework.Relational.Design'.
   at NuGet.Manifest.ValidateDependencySets(IPackageMetadata metadata)
   at NuGet.Manifest.ReadFrom(Stream stream, IPropertyProvider propertyProvider, Boolean validateSchema)
   at NuGet.Lucene.FastZipPackage.ReadManifest(Stream manifestStream)
   at NuGet.Lucene.FastZipPackage.Open(String originalFilePath, IHashProvider hashProvider)
   at NuGet.Lucene.LucenePackageRepository.OpenPackage(String path)
   at NuGet.Lucene.LucenePackageRepository.LoadFromFileSystem(String path)
   at NuGet.Lucene.PackageIndexer.SynchronizePackage(String path)
```

I haven't seen this type of problem reported until now.

It might be worthwhile to try a beta build of Klondike 2.0, available from
https://ci.appveyor.com/project/chriseldredge/klondike/build/artifacts to see if the
new version has the same problems.

I'm in the unfortunate position of not wanting to support or fix 1.6.2 and yet I haven't released an official 2.0 version yet. Thanks for bearing with me :)

**Comment by chriseldredge** [comment]
What do you normally do to resolve this problem when it crops up? Manually delete the lock file? Terminate the worker process?

**Comment by tysonstewart** [comment]
I stop and start the web application pool. I haven't had to kill the w3wp.exe process. Interestingly, I haven't had to delete the lock file, either. When (or if) it happens again, I'll make sure to check if the file exists before I restart the app pool.

I'd like to consider updating to 2.0, but I'm a little hesitant since it's not released yet. Our development and deployment process relies pretty heavily on NuGet server and grinds to a halt if it's unavailable. Klondike is honestly amazing for us since the Microsoft NuGet Server package couldn't handle the load we were putting on it. Seriously, I can't thank you enough for this app!

**Comment by tysonstewart** [comment]
One other thing I tried today: I turned off the scheduled app pool recycling. I'm not sure if that was a great idea in case it results in total resource consumption, but I thought the act of recycling itself might be leading to the problem. If that turns out to stabilize things, I may schedule the recycle once a week on the weekends when no one is likely to be using it.

**Comment by chriseldredge** [comment]
Does the Windows Event Log have any events related to the Klondike app pool terminating due to an exception? I'm wondering if somehow the app domain is crashing and the lock file is left after the process exits. This would prevent the app from starting back up until you manually remove the lock file.

**Comment by tysonstewart** [comment]
No, there actually aren't any events at all for 45 minutes prior to the first error, which is the one about the lock file. 

The good news is that it hasn't crashed since I last posted. The potentially bad news is that memory usage has gone from 25% to 65% during that time. It's currently using about 2.7GB. It will be interesting to see what happens when it maxes out. We'll probably schedule a regular weekly restart.

**Comment by chriseldredge** [comment]
I haven't done all that much memory-based load testing but I believe that the garbage collector will work effectively and you shouldn't run into an OOM situation under normal circumstances.

The data provider will cache heavily but that cache gets invalidated every time a package is pushed, deleted or downloaded. The .NET framework will generally by happy to consume available system memory until it can't anymore at which time it'll get a little more aggressive with running GC collections more frequently.

I'll be interested to hear your results, but I've been running 2 Klondike servers for many years with app pool recycling completely disabled on both. No OOM problems in my world :)

**Comment by tysonstewart** [comment]
That is some good info! Thanks for your help in this.
