### ISSUE TITLE
IIS Worker Process 100% CPU

### ISSUE THREAD

**Issue by ajcurtin** [themotleyfool/Klondike#97]
Hi,

I have been using klondike as my nuget feed server for Octopus for a while and recently the IIS worker process for the klondike app pool has been throttling the cpu constantly at 100%. This means that Octopus deploy times out trying to grab packages from Klondike.

Any ideas as to what adjustments I need to make to get this working again? I just tried updating to latest Klondike release and have messed with the app pool/recycling and ensured all the app pool settings are correct.

**Comment by chriseldredge** [comment]
By latest release do you mean 1.6.2? You could try optimizing the index by doing something like `curl -d '' http://localhost/api/indexing/optimize` which depending on your security settings may require sending the `X-NuGet-ApiKey` header.

You can also try a beta build of Klondike 2.0 available from https://ci.appveyor.com/project/chriseldredge/klondike/build/artifacts

If you try a new build, make sure to rebuild your index by clicking the button on the Admin screen.

How many packages are in your feed? Do you have any process to delete unused or old builds that you don't need anymore?

**Comment by chriseldredge** [comment]
Closing. Need more info to help troubleshoot.
